solarwinds/apm-python

CHANGELOG.md
solarwinds_apm/sampler.py
tests/unit/test_sampler/test_sampler_calculate_attributes.py

Bugfix: custom sampler's `calculate_attributes` now adds existing attributes earlier. This is important for scenarios where the customer uses the SDK to start spans with custom attributes, e.g.
```
with tracer.start_as_current_span(
"manual_instrumentation_django_a",
attributes={"foo-django-a": "bar-django-a"},
):
```
Example trace with this fix: https://my.na-01.st-ssp.solarwinds.com/136444677275740160/traces/6D23EB224226CC4A59FA70D95C0BB1BE/892E8BFFDE370C5D/details/789BCA3EB9F3A9A0/rawData which was created using this WIP testbed update: https://github.com/appoptics/solarwinds-apm-python-testbed/pull/45
Add a unit tests. All are passing.

NH-30870 calculate_attributes adds existing attrs earlier

---

CHANGELOG.md
solarwinds_apm/apm_config.py
solarwinds_apm/configurator.py
tests/unit/test_apm_config.py

This implements `"Idea #2"`, the unification of `OTEL_SERVICE_NAME`, `OTEL_RESOURCE_ATTRIBUTES`, and `SW_APM_SERVICE_KEY` for setting `service.name` in OTel resource attributes used by the configured TracerProvider. Details are here: https://swicloud.atlassian.net/wiki/spaces/NIT/pages/3379855366/OTel+vs+SWO+Service+Name?focusedCommentId=3388899356#Idea-#2:-Unify-OTEL_SERVICE_NAME-and-SW_APM_SERVICE_KEY
Summary: `SolarWindsApmConfig` is responsible for `_calculate_service_name` and uses a fresh OTel `Resource.create` (by default) to get OTel's calculation of `service.name` based on the `OTEL_*` env vars if provided. If there isn't an OTel service name, we use `SW_APM_SERVICE_KEY` instead. ApmConfig also updates its `service_key` value using that name. Then the Configurator uses ApmConfig …

NH-29850 unify OTel service name with SW_APM service key

---

CHANGELOG.md
solarwinds_apm/version.py
tests/docker/install/install_tests.sh

Testrelease of [solarwinds-apm 0.5.0.2](https://test.pypi.org/project/solarwinds-apm/0.5.0.2/) (https://swicloud.atlassian.net/browse/NH-29970), which I also released to test the fix for the install tests (https://swicloud.atlassian.net/browse/NH-31311).
Before this `install_tests.sh` update, install tests were failing for Python 3.10 and 3.11 on Ubuntu 18.04 and 20.04. There is something in the recent major release of `setuptools 66.0.0` this month that breaks with `InvalidVersion` errors at the call to `opentelemetry-bootstrap`. I will continue investigating whether this is a SolarWinds issue or an OTel issue for these Python versions on Ubuntu (https://swicloud.atlassian.net/browse/NH-31430). I just want to get this release out first!
SWO test trace: …

NH-29970 NH-31311 Testrelease 0.5.0.2 with fix for install tests

---

CHANGELOG.md
solarwinds_apm/exporter.py

This fixes a framework lookup at `Python.*.Version` span KV calculation and removes excessive warning logs as reported by customer, which are logging once per span, 3 spans per trace created by a very simple FastAPI app (their code [attached to ticket](https://swicloud.atlassian.net/browse/NH-32409), similar in [testbed PR here](https://github.com/appoptics/solarwinds-apm-python-testbed/pull/48)):
```[ solarwinds_apm.exporter WARNING  p#1.140549948016384] Version lookup of asgi failed, so skipping: No module named 'asgi'```
This is a bit of an odd approach but all of `SolarWindsSpanExporter._add_info_instrumented_framework` is a little odd. The exceptions were being raised (and caught to log) because we can't `import asgi` to get its version. Instead, ASGI design is implemented by several …

NH-32409 Fix failed ASGI version lookup logs

---

CHANGELOG.md
solarwinds_apm/version.py

Test publish of solarwinds-apm 0.6.0.24 to TestPyPI (`x86_64` only):
https://test.pypi.org/project/solarwinds-apm/0.6.0.24/
Test traces:
* NH prod: https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/E3E5353038573EC1804FCBA02866344C/4E8927A23CA41106/details
* AO prod: https://my.appoptics.com/apm/123092/services/django-app-a-ot/traces/C5723087D04100E80F96264FFA9BED8100000000/graph
Install tests pass: https://github.com/solarwindscloud/solarwinds-apm-python/actions/runs/4127805557
Updates since 0.5.0:
```
- SolarWinds c-lib 12.0.0, for gRPC upgrade ([#107](https://github.com/solarwindscloud/solarwinds-apm-python/pull/107))
- Bugfix: fix version lookup failures for instrumented ASGI libraries ([#108](https://github.com/solarwindscloud/solarwinds-apm-python/pull/108))
- Drop …
```

NH-32619 Testrelease 0.6.0.24

---

.github/workflows/codeql_analysis.yml

Updates Python APM library repo's existing CodeQL workflow config to use newer actions and advanced queries, and trigger on PR/push to `main`.
Seems to work:
* Last run finished without errors: https://github.com/solarwindscloud/solarwinds-apm-python/actions/runs/4198829934/jobs/7282953892
* resulting in CodeQL suggestions in the [Files changed](https://github.com/solarwindscloud/solarwinds-apm-python/pull/112/files) of this PR under "Unchanged files with check annotations"! (I'll address these in a different PR.)
* No scanning alerts, which I'm still a bit skeptical about: https://github.com/solarwindscloud/solarwinds-apm-python/security/code-scanning

ENOPS-3865 update codeql workflow

---

CHANGELOG.md
solarwinds_apm/version.py

Testrelease 0.7.0.5 before prod/PyPI release.
x86_64 and AARCH64 artifacts published to: https://test.pypi.org/project/solarwinds-apm/0.7.0.5/#files
Installation tests for both pass: https://github.com/solarwindscloud/solarwinds-apm-python/actions/runs/4245798590

Testrelease 0.7.0.5

---

CHANGELOG.md
dev-requirements.txt
setup.cfg

Bump Otel Python 1.16.0-0.370b.
NH test trace: https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/229240F1497484FE0309209D459ED26D/FC8FB4720A6096C0/details/breakdown
AO test trace: https://my.appoptics.com/apm/123092/services/django-app-a-ot/traces/270BE597ECE91DD1D1BF843ADFDAD32100000000/graph
tox tests passing.

NH-33743 Bump Otel Python 1.16.0-0.370b

---

CHANGELOG.md
setup.cfg
solarwinds_apm/version.py
tests/docker/install/install_tests.sh

Updates since 0.7.0 (this PR also includes an install test and packaging fix):
```
- Add `set_transaction_name` API method ([#115](https://github.com/solarwindscloud/solarwinds-apm-python/pull/115))
- Deprecated `solarwinds_apm.apm_ready.solarwinds_ready`. Instead, use `solarwinds_apm.api.solarwinds_ready`. ([#115](https://github.com/solarwindscloud/solarwinds-apm-python/pull/115))
- OpenTelemetry API/SDK 1.16.0 ([#116](https://github.com/solarwindscloud/solarwinds-apm-python/pull/116))
- OpenTelemetry Instrumentation 0.37b0 ([#116](https://github.com/solarwindscloud/solarwinds-apm-python/pull/116))
```
Published to TestPyPI as 0.8.0.2: https://test.pypi.org/project/solarwinds-apm/0.8.0.2/#files
- NH Django test trace: https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/B3435F0 …

Testrelease 0.8.0.2

---

CHANGELOG.md
solarwinds_apm/w3c_transformer.py
tests/unit/test_w3c_transformer.py

Delete xtraceoptions response from tracestate only if present. This is a bugfix to stop seeing this message that was logging at every single `should_sample` and `inject` call!:
```
The provided key xtrace_options_response doesn't exist.
```
tox tests pass on this PR. Exported test traces look ok on [SWO](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/8EFBD612CC33E3AD1449C5FAC5B2EEE8/D85D8DFFA57AB2B2/details/breakdown) and [AO](https://my.appoptics.com/apm/123092/services/django-app-a-ot/traces/CE85F367360102707800831E40B7DC5C00000000/details).

NH-34221 delete xtraceoptions response from tracestate only if present

---

CHANGELOG.md
solarwinds_apm/configurator.py
solarwinds_apm/exporter.py
tests/unit/test_exporter.py

This is a typo bugfix so that setting span attribute (event info) `Python.aiohttp.version` stops failing. This also stops this message from logging at every export of aiohttp client spans:
```
2023-02-17 23:13:31,732 [ solarwinds_apm.exporter WARNING  p#1.140602549180160] Version lookup of aiohttp_client failed, so skipping: No module named 'aiohttp_client'
```
tox tests pass on this PR. Exported test traces look ok on [SWO](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/97C0BA508EBC35465B30B16288AE291D/E7AD9949E5667C14/details/breakdown/D503276EA2A76ED4/rawData) and [AO](https://my.appoptics.com/apm/123092/services/asgi_app_ot/traces/0187432070FC0EE11138EC9300E224C300000000/span/31D7820D5A06782C), with the `HTTP GET` spans now including `Python.aiohttp.version`.

NH-33749 Fix typo in aiohttp_client lib lookups

---

CHANGELOG.md
solarwinds_apm/version.py

Testrelease 0.8.2.0. Updates since 0.8.1:
```
- Bugfix: fixed noisy trace state KV deletion attempts when key not present ([#121](https://github.com/solarwindscloud/solarwinds-apm-python/pull/121))
- Bugfix: fixed version lookup failures for instrumented aiohttp library ([#122](https://github.com/solarwindscloud/solarwinds-apm-python/pull/122))
```
Published as solarwinds-apm 0.8.2.0 on TestPyPI: https://test.pypi.org/project/solarwinds-apm/0.8.2.0/
tox tests pass on this PR. Install tests: https://github.com/solarwindscloud/solarwinds-apm-python/actions/runs/4389822972
Test traces:
* [NH Django](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/CE52D13639C6672A1BA5BA0C61DF3A6B/94EC4A3389FC7FE4/details/breakdown)
* [NH …

Testrelease 0.8.2.0

---

CHANGELOG.md
solarwinds_apm/api/__init__.py
solarwinds_apm/apm_config.py
solarwinds_apm/configurator.py
solarwinds_apm/exporter.py
solarwinds_apm/inbound_metrics_processor.py
solarwinds_apm/sampler.py
solarwinds_apm/version.py

Fixes errors at customer code calls to API `set_transaction_name` when `agent_enabled` False!:
```
File "/app/main.py", line 79, in reentry_async
set_transaction_name("custom-name-that-shouldnt-be-used")
File "/solarwinds-apm-python/solarwinds_apm/api/__init__.py", line 48, in set_transaction_name
get_tracer_provider()._active_span_processor._span_processors
AttributeError: 'NoOpTracerProvider' object has no attribute '_active_span_processor'
```
No longer errors when e.g. `Incorrect service key format.`, testbed ASGI app is run, and `curl -v http://0.0.0.0:8005/reentry_async` which includes calls to `set_transaction_name`.
Trace still exports when agent enabled and `set_transaction_name` calls work on entry spans: https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/0E45BB4C6DD …

NH-36210 Bugfix set_transaction_name when agent_enabled False + linting

---

CHANGELOG.md
solarwinds_apm/version.py
tests/docker/install/install_tests.sh

Testrelease 0.8.3.4 of Python APM library. Took a few tries with the install tests' checked warning message contact info update.
tox tests on this PR pass. Test traces:
* [NH Django](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/3B6508581B9C9E91ACB3E50912F3D3F9/988B3E723C40636A/details/breakdown)
* [NH FastAPI](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/3579DF13724B7542C05431217FA72495/819616850F00443F/details/breakdown)
* [AO Django](https://my.appoptics.com/apm/123092/services/django-app-a-ot/traces/C32A3D92F9BAD2658C354566C76F8D2000000000/details)
* [AO FastAPI](https://my.appoptics.com/apm/123092/services/asgi_app_ot/traces/6F905F9575E38677D75200B426B63FAD00000000/details)
Test published as [TestPyPI …

NH-36223 Testrelease 0.8.3.4

---

dev-requirements.txt
setup.cfg
solarwinds_apm/version.py

Bump Python APM to Otel 1.17.0/0.38b0. Goes with this [testbed PR](https://github.com/appoptics/solarwinds-apm-python-testbed/pull/57).
tox tests on this PR pass.
Test traces:
* [Django NH prod](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/3D3A5439D2FD9990863E5E6DDFC9C5D1/7E7C7DF82894A2DE/details/breakdown)
* [FastAPI NH prod](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/BCE5FF0F19D2E3ADF54E8DEF29AFD068/8F1DB0064F27CC7A/details/breakdown)
* [Django AO prod](https://my.appoptics.com/apm/123092/services/django-app-a-ot/traces/EE3F61FF60587AA5881BB57A5DBBAAB300000000/details)
* [FastAPI NH prod](https://my.appoptics.com/apm/123092/services/asgi_app_ot/traces/B8AAC59F1337E377DF5F3A7B5246377400000000/details)
Testreleased as [TestPyPI …

NH-36371 Bump Otel Python 1.17.0/0.38b0

---

solarwinds_apm/apm_config.py

Implements the stub for `update_with_cnf_file` and adds a helper `update_transaction_filters`. Both read values from a customer file at `SW_APM_CONFIG_FILE` else the default `./solarwinds-apm-config.json`, to copy what [Java APM](https://documentation.solarwinds.com/en/success_center/observability/content/configure/services/java/configure.htm#link10) does. Values are stored in the `SolarWindsApmConfig` init'd by Configurator and passed to our custom Otel components at service startup.
The config file JSON keys are a bit different than Java. Example:
* config file: `triggerTrace`
* env var: `SW_APM_TRIGGER_TRACE`
All thoughts/questions welcome!
Next PRs:
* Actually use `transaction_filters` at `should_sample`
* infodev/customer docs update

NH-34752 Add config JSON file support

---

solarwinds_apm/apm_config.py
solarwinds_apm/sampler.py
tests/unit/test_apm_config.py
tests/unit/test_sampler/fixtures/sampler.py
tests/unit/test_sampler/test_sampler.py

This is more steps towards implementing transaction filtering:
1. Update `update_transaction_filters` in the Configurator to use existing helper `OboeTracingMode.get_oboe_trace_mode` to map filter's `tracing` to int for liboboe
2. Also more checks for valid filter's `regex` values
3. Adds `calculate_tracing_mode` used by sampler to apply per-request filter or "global" `tracing_mode` that can also be configured.
This only filters for span `<kind>:<name>` right now because `http.*` attributes generated by instrumentation libraries are not yet available to the sampler, but this is gradually being implemented in [OTel #936](https://github.com/open-telemetry/opentelemetry-python-contrib/issues/936).
Example basic config file JSON I'm using with Django A:
```
{
"tracingMode": "enabled", …
```

NH-34752 Parse txn filters and calculate tracing mode

---

solarwinds_apm/sampler.py

Adds `construct_url` helper for `calculate_tracing_mode`. I've done it this way so that if there is a URL, it gets used as the identifier and the customer has no choice for filtering (see also [Slack thread](https://swicloud.slack.com/archives/C2J43PE4R/p1682363645105209?thread_ts=1682098813.423939&cid=C2J43PE4R)). At the moment it will always return empty string until a new version of `opentelemetry-python-contrib` is released, so more testing will come later. This is set to merge into https://github.com/solarwindscloud/solarwinds-apm-python/pull/136.

NH-34752 Add construct_url for calculate_tracing_mode

---

tests/unit/test_sampler/fixtures/sampler.py
tests/unit/test_sampler/test_sampler.py
tests/unit/test_sampler/test_sampler_calculate_attributes.py
tests/unit/test_sampler/test_sampler_calculate_tracing_mode.py

Adds unit tests for `calculate_tracing_mode` and `construct_url`, with a new fixture for a sampler with some transaction filters set.
The source code was introduced in https://github.com/solarwindscloud/solarwinds-apm-python/pull/136/files and https://github.com/solarwindscloud/solarwinds-apm-python/pull/137/files.
EDIT: In [b7180d5](https://github.com/solarwindscloud/solarwinds-apm-python/pull/138/commits/b7180d5520f53ccfd3394eba6fcbba5e7ce7f9ab) I've renamed both sampler fixtures for general clarity and to try to make CodeQL happy.

NH-34752 Add calculate_tracing_mode tests and fixture

---

solarwinds_apm/apm_config.py
tests/unit/test_apm_config/fixtures/cnf_dict.py
tests/unit/test_apm_config/fixtures/cnf_file.py
tests/unit/test_apm_config/fixtures/env_vars.py
tests/unit/test_apm_config/test_apm_config.py
tests/unit/test_apm_config/test_apm_config_cnf_file.py

This mainly adds config file support tests. Changes:
1. Moves existing `test_apm_config.py` to its own subdir
2. Adds new test fixtures/mocks for return of Python with-file-open, `get_cnf_dict` helper.
3. Adds new `test_apm_config_cnf_file.py` to test different scenarios for config file reading, updating config using file (with or without env vars also specified). 
This PR also includes some small code changes:
1. Removes unused configs `inst` and `inst_enabled` that were copied from AO but won't be in SWO
2. Refactors `get_cnf_dict` helper out of existing `update_with_cnf_file` for easier testing
Since code was changed, here is a [test trace](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/8450F96B6EC34545BCD92147F53814EE/1CA019D0173930C9/details/breakdown?perspective=requ …

NH-34752 Add config file tests + small changes

---

solarwinds_apm/apm_config.py
tests/unit/test_apm_config/fixtures/cnf_dict.py
tests/unit/test_apm_config/test_apm_config_cnf_file.py

Remove unused `prepend_domain_name` from Python APM config support. This was copied from AO but is not actually used for SWO transaction naming.
If we support this feature in the future, consider a flat config as mentioned in this [PR comment](https://github.com/solarwindscloud/solarwinds-apm-python/pull/139#discussion_r1179162323) and [NH-39702](https://swicloud.atlassian.net/browse/NH-39702):
```
{
"transactionPrependDomain": false,
"transactionSettings": []
}
```
tox tests pass, and here is a manual test trace: https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/CB138A762D313C5093BAAF9ADC2D47BA/67820577B5756263/details/breakdown?perspective=requests&serviceId=e-1540126275982954496
[NH-39702]: https://swicloud.atlassian.net/browse/NH-39702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmND …

NH-39702 Remove unused prepend_domain_name from config

---

CHANGELOG.md
solarwinds_apm/exporter.py
tests/unit/test_exporter.py

Add `sw.span_name` attribute at export as per [acceptance criteria](https://swicloud.atlassian.net/wiki/spaces/NIT/pages/3538485339/Transaction+Filtering+aka+per-request+tracing+mode#Acceptance-Criteria).
I've added the test case's additional expected call `mocker.call("TransactionName", "foo")` because we've gone from a mock txn name manager with unspecified `get` method (which does magic mocking) to an explicit one.
[Example trace](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/C2B6EB747B271FAE44CF17A17E7F1A6C/5267657C46A48D38/details/breakdown/5267657C46A48D38/raw-data?perspective=requests&serviceId=e-1540126275982954496) with `sw.span_name` included in the exported spans.

NH-34752 Add sw.span_name attribute at export

---

solarwinds_apm/apm_config.py
tests/unit/test_apm_config/test_apm_config_cnf_file.py
tests/unit/test_apm_config/test_apm_config_transaction_filters.py

Adds unit tests for `update_transaction_filters`, which revealed a bug with how multiple customer filters are handled. Bugfix included in b616f96 so `test_update_transaction_filters_multiple_regex_use_first` passes.
[Test trace](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/69C88A691A90F1F650751BE660E53989/28B84DBFEE997D6A/details/breakdown?perspective=requests&serviceId=e-1540126275982954496) since source code changed. This was for a request that was not filtered out, whereas those filtered out did not trace with flag `00`. 
EDIT: I missed a test case update for #140 so added here in [9a7fb98](https://github.com/solarwindscloud/solarwinds-apm-python/pull/141/commits/9a7fb9848946df8de794284f8095ea7805821fd7).

NH-34752 Add txn filter unit tests and bugfix

---

solarwinds_apm/apm_config.py

Adjusts some config-related logging that was a little misleading.
If `SW_APM_CONFIG_FILE` is not set, the default is used (`./solarwinds-apm-config.json`). A config file actually being there should be optional, but instead error logs every time: `[ solarwinds_apm.apm_config ERROR    p#1.139799927957312] Invalid config file path. Ignoring: [Errno 2] No such file or directory: './solarwinds-apm-config.json'`
If no transaction filters are provided, including when if no config file is provided, then this is ok. But this message isn't great when that's the case: `[ solarwinds_apm.apm_config WARNING  p#1.140511341504320] Transaction filters must be a non-empty list of filters. Ignoring.`
If `SW_APM_CONFIG_FILE` is not set and there is no file at the default `./solarwinds-apm-config.json`, there …

NH-40333 Adjust config-related logging

---

CHANGELOG.md
dev-requirements.txt
setup.cfg

Bumps Python APM to latest Otel Python 1.18.0/0.390b.
Test traces:
* [SWO Django trace](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/FA3CB76CA143FB47B48EE20B92659E4D/5D7919D6503DF943/details/breakdown?perspective=requests&serviceId=e-1540126275982954496)
* [SWO FastAPI trace](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/1A50BEA107273B530D29CF1A7CC49E68/2FB153D1E9770FC3/details/breakdown?perspective=requests&serviceId=e-1563388155741380608)
* [AO Django trace](https://my.appoptics.com/apm/123092/services/django-app-a-ot/traces/D14D92CF5E8BDB27A4663678ED38B43800000000/details)
* [AO FastAPI trace](https://my.appoptics.com/apm/123092/services/asgi_app_ot/traces/BE59591BEF175540A1B09928E2957CA500000000/details)

NH-39995 Bump Otel Python 1.18.0/0.39b0

---

setup.cfg
solarwinds_apm/distro.py
tox.ini

~~Do not merge until after this is on main: https://swicloud.atlassian.net/browse/NH-39995~~ EDIT: Done ✅ 
Adds a custom distro-side default for `OTEL_PYTHON_LOG_FORMAT` which is used by [opentelemetry-logging-instrumentation](https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-logging) to set format of all logs from Python `logging` module and include trace context information. It's a default, so customer can still specify their own `OTEL_PYTHON_LOG_FORMAT` by environment variable.
Default format is:
`%(asctime)s %(levelname)s [%(name)s] [%(filename)s:%(lineno)d] [trace_id=%(otelTraceID)s span_id=%(otelSpanID)s trace_flags=%(otelTraceSampled)02d resource.service.name=%(otelServiceName)s] - %(message)s`
Example log with …

NH-29380 Add distro default OTEL_PYTHON_LOG_FORMAT

---

.github/workflows/verify_install.yaml
CHANGELOG.md
solarwinds_apm/version.py
tests/docker/install/_helper_run_install_tests.sh
tests/docker/install/client.py
tests/docker/install/docker-compose.yml

Testrelease Python APM 0.11.0.4. This branch also includes some install test updates:
1. Switch from Amazon 2 to Amazon 2023 install testing as per upstream urllib3 v2.0 update [recommendations](https://urllib3.readthedocs.io/en/latest/v2-migration-guide.html#common-upgrading-issues).
2. Remove a stray Amazon 2018 install test because it's [EOL Dec 31 2020](https://endoflife.date/amazon-linux) and we don’t list it on the [customer docs](https://documentation.solarwinds.com/en/success_center/observability/content/system_requirements/apm_requirements.htm#operating-systems)
3. Add a sleep to the install tests before the client makes requests to the test Flask server, to address https://swicloud.atlassian.net/browse/NH-40332.
Test traces:
* [SWO Django …

NH-41682 Testrelease 0.11.0.0

---

.github/workflows/verify_install_arm64.yaml

Adds stub for verify_install_arm64.yaml that uses https://github.com/solarwindscloud/ec2-runner-action. Adds two jobs in matrix that will `echo` to make sure new secrets work. After this PR to `main` I can run the action with dispatch and update it.

NH-41991 Add stub for verify_install_arm64.yaml

---

tests/docker/install/docker-compose.yml

Fixes yaml used to run Python APM install tests locally, after recent docker-compose update. 😬 
Related: https://github.com/docker/compose/issues/10411

Fix yaml after docker-compose update

---

.github/workflows/verify_install.yaml
CHANGELOG.md
tests/docker/install/_helper_run_install_tests.sh
tests/docker/install/client.py
tests/docker/install/docker-compose.yml
tests/docker/install/install_tests.sh

Removes the part of the install_tests script that uninstalls the latest `setuptools` and installs an older version, because this is no longer needed. `opentelemetry-bootstrap` now works ok with current `setuptools`.
Also adds local and GH install test containers for Ubuntu 22 and py3.10/3.11. Ubuntu 22 does not need to use `deadsnakes` to install Python but Ubuntu 20 still needs it.
GH test run: https://github.com/solarwindscloud/solarwinds-apm-python/actions/runs/5138153171

NH-31430 Add Ubuntu 22, use current setuptools in install tests

---

CHANGELOG.md
solarwinds_apm/version.py

Testrelease 0.12.0.0
Published to TestPyPI: https://test.pypi.org/project/solarwinds-apm/0.12.0.0/
Install tests pass, now on EC2 runners 🌟 : https://github.com/solarwindscloud/solarwinds-apm-python/actions/runs/5149464209
tox tests on this PR pass.
e2e test traces:
* [SWO Django](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/C7EB3037E209D4B5A73D8DA4D703A93E/F860E61FDD992E94/details/breakdown?perspective=requests&serviceId=e-1540126275982954496&sort_by_breakdown=SpanLayer&sort_order_breakdown=ascending)
* [SWO FastAPI](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/B3A87695E654C458B4C76DB174BF1FB6/3674B8BC9DCE4C81/details/breakdown?perspective=requests&serviceId=e-1563388155741380608)
* [AO Django](https://my.appoptics.com/apm/123092/services/django-app-a …

NH-42174 Testrelease 0.12.0.0

---

CHANGELOG.md
solarwinds_apm/api/__init__.py

If customers call `set_transaction_name("")` with an empty string, there will now be a warning log and the method will return `False`. I've commented on the [hijacked spec doc](https://swicloud.atlassian.net/wiki/spaces/NIT/pages/3601400601/Swo-SDK+Application+Programming+Interface?focusedCommentId=3620274549) to confirm, and Java library is doing this too: https://github.com/appoptics/solarwinds-apm-java/pull/105/files
Before this change, Python relies on falsiness to not use empty string nor None as transaction name: https://github.com/solarwindscloud/solarwinds-apm-python/blob/main/solarwinds_apm/inbound_metrics_processor.py#L171 So what's exported to SWO doesn't change with this PR.
I've also adjusted log severity of other parts of the method, though I'm not sure what's best with the …

NH-42458 set_transaction_name empty name case

---

CHANGELOG.md
solarwinds_apm/apm_config.py
tests/unit/test_apm_config/test_apm_config.py
tests/unit/test_apm_config/test_apm_config_cnf_file.py

I'm working on documentation updates and found `log_trace_id` in APM Python config. This is not used and will not be needed because the distro leverages existing Otel Python instrumentation library completely for the trace context in logs feature and it makes no sense to me to have an extra layer: https://documentation.solarwinds.com/en/success_center/observability/content/configure/services/python/configure.htm#link17. So I'm removing all mentions and storage of this value.

NH-29380 Remove unused log_trace_id config

---

CHANGELOG.md
solarwinds_apm/apm_config.py
tests/unit/test_apm_config/fixtures/cnf_dict.py
tests/unit/test_apm_config/test_apm_config.py
tests/unit/test_apm_config/test_apm_config_agent_enabled.py

This fixes the accepted values for those APM Python configs that are booleans... which is really only `SW_APM_AGENT_ENABLED` after #163, #164, #165. Other similar configs accept "enabled"/"disabled".
The customer can now set bool (from JSON config) or case-insensitive string rep of bool (from JSON config or env vars) (e.g. `"true"`, `"False"`, `"fALsE"`). Integers are ignored, which is different from [AO Python](https://documentation.solarwinds.com/en/success_center/appoptics/content/kb/apm_tracing/python/configure.htm?cshid=appoptics_kb/apm_tracing/python/configure/#booleans-note) and imo less complicated. Therefore I've moved and repurposed the method `_convert_to_bool`. More tests added too.
Please let me know what you think 😺

NH-29380 Fix accepted config bool values

---

.github/actions/package_solarwinds_apm_aarch64/action.yaml
.github/workflows/build_publish_packagecloud.yaml
.github/workflows/build_publish_pypi_and_draft_release.yaml
.github/workflows/build_publish_testpypi.yaml
CHANGELOG.md
solarwinds_apm/version.py

Updates APM Python build workflows to use our [ec2-runner-action](https://github.com/solarwindscloud/ec2-runner-action) (fast) instead of QEMU (slow), required for aarch64 support.
The TestPyPI publish was successful for testrelease 0.12.2.2:
* https://github.com/solarwindscloud/solarwinds-apm-python/actions/runs/5468641263
* https://test.pypi.org/project/solarwinds-apm/0.12.2.2/#files
The resulting sdist and wheels seem ok as smoke/install-from-testpypi tests passed: https://github.com/solarwindscloud/solarwinds-apm-python/actions/runs/5468792291
The x86_64 builds still run first and separately on GHA runners. For readability I'll merge them in a future PR.
Please let me know what you think!

NH-42453 Build APM Python on EC2

---

CHANGELOG.md
solarwinds_apm/apm_config.py
tests/unit/test_apm_config/test_apm_config.py

Metric format is `TransactionResponseTime` when reporting to AO (same as before) or `ResponseTime` when reporting to SWO (instead of both). Also simplified the condition.

NH-44210 metric format one or other not both

---

.github/workflows/build_publish_packagecloud.yaml
.github/workflows/build_publish_pypi_and_draft_release.yaml
.github/workflows/build_publish_testpypi.yaml
.github/workflows/create_release_pr.yaml
.github/workflows/verify_install.yaml

Not necessary but I wanted some clarity! Following their rotation, I'm updating the CI creds in 2 steps -- I've added the new ones then I'll delete the old ones after this is merged). I like the names of the new ones better to [match the doc](https://github.com/solarwindscloud/apm-ci-infra).
Tested with the Verify Install action: https://github.com/solarwindscloud/solarwinds-apm-python/actions/runs/5592768100

NH-47761 Renamed secrets for clarity of CI creds

---

dev-requirements.txt
setup.cfg
tests/integration/test_scenario_1.py
tests/integration/test_scenario_4.py
tests/integration/test_scenario_8.py
tests/integration/test_signed_tt.py
tests/integration/test_unsigned_tt.py

Upgrade to Otel Python 1.19.0/0.40b0
* https://github.com/open-telemetry/opentelemetry-python/releases/tag/v1.19.0
* https://github.com/open-telemetry/opentelemetry-python-contrib/releases/tag/v0.40b0
Integration tests are updated I think because new OTel Python includes the Flask instrumentation update PR: https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1784
Test traces:
* [SWO Django](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/B1D184BEFC24F7F1CCE4A292BA32517B/943B2952D185D7DD/details/breakdown?perspective=requests&serviceId=e-1540126275982954496&sort_by_breakdown=spanLayer&sort_order_breakdown=ascending)
* [SWO FastAPI](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/B3AA1BB4CC3EAC69FED8FCF70E7ACAD7/6CBFB …

NH-46870 Otel Python 1.19.0/0.40b0

---

CHANGELOG.md
solarwinds_apm/version.py

For PyPI release of solarwinds-apm 0.14.0. See also CHANGELOG.md.
Test traces from local install:
- [SWO Django](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/646D40220C53017B4FD546980D1FD86B/77BB572D5B5B83C9/details/breakdown?perspective=requests&serviceId=e-1540126275982954496&sort_by_breakdown=spanLayer&sort_order_breakdown=ascending)
- [SWO FastAPI](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/ED1613AB485755397A49AE3943367A80/56540D50CECAB67D/details/breakdown?perspective=requests&serviceId=e-1563388155741380608&sort_by_breakdown=spanLayer&sort_order_breakdown=ascending)
- [AO Django](https://my.appoptics.com/apm/123092/services/django-app-a-ot/traces/77FE22144784C4195C06FE949185302F00000000?duration=3600)
- [AO …

solarwinds-apm 0.14.0

---

solarwinds_apm/apm_config.py
solarwinds_apm/distro.py
tests/unit/test_apm_config/test_apm_config.py
tests/unit/test_distro.py

Updates APM Python custom distro to read and parse `OTEL_SQLCOMMENTER_OPTIONS` if set by customer and if `OTEL_SQLCOMMENTER_ENABLED=true`. The options are used to init all Otel Python instrumentors that have a sqlcommenting feature. For more details please see ["How the two env vars work" section](https://swicloud.atlassian.net/wiki/spaces/NIT/pages/3704816080/2023-07-24+OTEL+SQLCOMMENTER+OPTIONS+testing#How-the-two-env-vars-work).
This also refactors existing `ApmConfig.convert_to_bool` as a class method so the distro class can also use it. Not ideal so let me know if it should be in its own class or some other way.
Unit tests added and updated.
Tested manually with results starting in ["Results" section](https://swicloud.atlassian.net/wiki/spaces/NIT/pages/3704816080/2023-07-24+OTEL+SQLC …

NH-46327 APM Python accepts OTEL_SQLCOMMENTER_OPTIONS

---

solarwinds_apm/inbound_metrics_processor.py
tests/unit/test_inbound_metrics_processor.py

EDIT: Also adds several unit tests for inbound metrics processor.
Adds removal of any stored custom transaction name at the end of `calculate_custom_transaction_name`. It will only be re-added to the manager if span is sampled so that exporter will have access to the name, before removing name again after reporting. This is to stop leaking in the case where span is _not_ sampled but custom transaction name is set (used for inbound metrics reporting). Big thanks to @swi-jared for seeing this!
Step-wise:
1. Customer code calls `set_transaction_name("foo")`. Call is successful and manager stores `"<trace_id>-<span_id>": "foo"`.
2. Otel SDK ends span with that `<span_id>` and `on_end` of processors called for all recorded spans, sampled or not (already in place!)
3. …

NH-52515 Remove cached custom name at calculate_custom

---

CHANGELOG.md
solarwinds_apm/api/__init__.py
solarwinds_apm/version.py

APM Python testrelease 0.15.0
(Accidentally published without usual 4th digit but should be ok on TestPyPI).
This also changes a `warning` level log back to `debug`, which it was before an accidental change in this PR: https://github.com/solarwindscloud/solarwinds-apm-python/pull/186/files.
tox tests on this PR pass.
Test traces:
* [SWO Django](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/E24082C8B84994EA9AE6523BC5025E52/9261777F2E12D9D9/details/breakdown?perspective=requests&serviceId=e-1540126275982954496&sort_by_breakdown=spanLayer&sort_order_breakdown=ascending)
* [SWO FastAPI](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/23E32CC384D4F01B35410A895A398A03/FD48C7BA1A592952/details/breakdown?perspective=requests&serviceId=e-1563388155741380608&sort_by …

NH-53373 Testrelease 0.15.0

---

CHANGELOG.md
solarwinds_apm/version.py

For PyPI release of solarwinds-apm 0.15.0. See also CHANGELOG.md.
tox tests on this PR pass.
Test traces:
- [SWO Django](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/E24082C8B84994EA9AE6523BC5025E52/9261777F2E12D9D9/details/breakdown?perspective=requests&serviceId=e-1540126275982954496&sort_by_breakdown=spanLayer&sort_order_breakdown=ascending)
- [SWO FastAPI](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/23E32CC384D4F01B35410A895A398A03/FD48C7BA1A592952/details/breakdown?perspective=requests&serviceId=e-1563388155741380608&sort_by_breakdown=spanLayer&sort_order_breakdown=ascending)
- [AO Django](https://my.appoptics.com/apm/123092/services/django-app-a-ot/traces/977875BA4CCA7E211E99D3F71CD0E71E00000000?duration=3600)
- [AO …

solarwinds-apm 0.15.0

---

CHANGELOG.md
solarwinds_apm/version.py

For PyPI release of solarwinds-apm 0.16.0. See also CHANGELOG.md.
Test traces:
* [SWO Django](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/0D5C6E2BB79681DC895223A4A16736A2/4C71F8952AB0287E/details/breakdown?perspective=requests&serviceId=e-1540126275982954496&sort_by_breakdown=spanLayer&sort_order_breakdown=ascending)
* [SWO FastAPI](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/ED23FBCE98D4410588A086DE3D3DB3F0/E03BA554F9101F12/details/breakdown?perspective=requests&serviceId=e-1563388155741380608&sort_by_breakdown=spanLayer&sort_order_breakdown=ascending)
* [AO Django](https://my.appoptics.com/apm/123092/services/django-app-a-ot/traces/6072BE56E7F632F324A77375E7DBA92C00000000?duration=3600)
* [AO …

solarwinds-apm 0.16.0

---

CHANGELOG.md
dev-requirements.txt
setup.cfg

Upgrades to Otel Python 1.12.0/0.41b0.
tox tests pass.
Test traces:
* [Django SWO](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/013431437E8E86DD71CAF2B4F71F8FD7/5560F46E6D1BEA1F/details?perspective=requests&serviceId=e-1540126275982954496)
* [FastAPI SWO](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/6584BD13A4C445762871DFDCED90A76E/6614567363DA65C7/details/breakdown?perspective=requests&serviceId=e-1563388155741380608)
* [Django AO](https://my.appoptics.com/apm/123092/services/django-app-a-ot/traces/CA1EC61D2ACC70CFFD90D359C8F50D7900000000?duration=3600)
* [FastAPI SWO](https://my.appoptics.com/apm/123092/services/asgi_app_ot/traces/491489EA97ACC4E5A192E68896839C1800000000?duration=3600)

NH-58212 APM Python to Otel 1.12.0/0.41b0

---

CHANGELOG.md
solarwinds_apm/version.py

Test release publish of version 0.17.0.2. Note that versions 0.17.0.0, 0.17.0.1 were used for PoC of APM Python lambda layer creation ([this PR](https://github.com/solarwindscloud/solarwinds-apm-python/pull/197)) with a Reporter init hardcoded kwarg and a revert. This version 0.17.0.2 does _not_ include those PoC changes and they will not be included in the next publish to prod/PyPI.
Published at TestPyPI: https://test.pypi.org/project/solarwinds-apm/0.17.0.2/
Test traces:
* [SWO Django](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/DC7A3C2600232FE6E2822E63AB6B0CD2/BD5D0D538EF5D20B/details/breakdown?perspective=requests&serviceId=e-1639104873316855808&sort_by_breakdown=spanLayer&sort_order_breakdown=ascending)
* [SWO …

NH-59208 Testrelease 0.17.0.2

---

CHANGELOG.md
solarwinds_apm/version.py

For PyPI release of solarwinds-apm 0.17.0. See also CHANGELOG.md.
Test traces:
* [SWO Django](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/DC7A3C2600232FE6E2822E63AB6B0CD2/BD5D0D538EF5D20B/details/breakdown?perspective=requests&serviceId=e-1639104873316855808&sort_by_breakdown=spanLayer&sort_order_breakdown=ascending)
* [SWO FastAPI](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/E8A58AD41392C0332BEB7CC363AA87C9/41E62FE4605E682B/details/breakdown?perspective=requests&serviceId=e-1563388155741380608&duration=3600&sort_by_breakdown=spanLayer&sort_order_breakdown=ascending)
* [AO Django](https://my.appoptics.com/apm/123092/services/django-app-a-ot/traces/228B4F90977FFD7B92AC2EDE4CB2E8A500000000?duration=3600)
* [AO …

solarwinds-apm 0.17.0

---

dev-requirements.txt

Adjust tox dev-requirements file's Flask dependency so that it matches that of the current upsteam Otel Python Flask instrumentor ([this pyproject.toml](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/e318c947a23152c8ff1700f0aad44261be0588cd/instrumentation/opentelemetry-instrumentation-flask/pyproject.toml#L37-L39)):
```
instruments = [
"flask >= 1.0, < 3.0",
]
```
The lack of Flask version restriction started making the APM Python automated tests fail with the release of Flask 3.0.0 two days ago (https://github.com/pallets/flask/releases/tag/3.0.0): `ERROR    opentelemetry.instrumentation.instrumentor:instrumentor.py:105 DependencyConflict: requested: "flask >= 1.0, < 3.0" but found: "flask 3.0.0"`.
Trying to instrument a Flask 3 app with plain upstream Otel Python …

NH-62605 tox test Flask dependency matches upstream instrumentor

---

.github/workflows/build_publish_pypi_and_draft_release.yaml
.github/workflows/build_publish_testpypi.yaml
.github/workflows/create_release_pr.yaml
.github/workflows/verify_install.yaml
solarwinds_apm/version.py

Updates PAT setup for workflows using EC2 runner action. No more use of `secrets.APM_CI_GHA_GITHUB_TOKEN`! (I had this naming set up instead of `secrets.CI_GITHUB_TOKEN`.) Will remove the secret after merging this.
Ran the Verify Install tests (download APM Python from prod) and they worked: https://github.com/solarwindscloud/solarwinds-apm-python/actions/runs/6425692600
Did a testrelease [0.18.0.1](https://test.pypi.org/project/solarwinds-apm/0.18.0.1/) using contents of this branch and that also worked: https://github.com/solarwindscloud/solarwinds-apm-python/actions/runs/6425811924/job/17449163590

NH-62722 Update PAT setup for workflow EC2 runners

---

CHANGELOG.md
solarwinds_apm/api/__init__.py
solarwinds_apm/apm_config.py
solarwinds_apm/inbound_metrics_processor.py
tests/unit/test_inbound_metrics_processor.py

Adds support for environment variable `SW_APM_TRANSACTION_NAME` or JSON config file `"transactionName"` to apply one custom name to all transactions. This is being introduced now for lambda instrumentation but is available outside of lambda too.
Precendence in decreasing order:
1. In-code call to existing `solarwinds_apm.api.set_transaction_name`
2. Environment variable `SW_APM_TRANSACTION_NAME` or config file KV
3. Then c-lib calculation of final txn name based on Otel span ingredients provided by language agent.
Tested manually with testbed [flask_apm_api_app](https://github.com/appoptics/solarwinds-apm-python-testbed/blob/main/flask_apm_api_app/app.py#L12). When the `set_transaction_name` call is commented out and `SW_APM_TRANSACTION_NAME` is set, the env var is used to name the …

NH-65075 Add support for SW_APM_TRANSACTION_NAME

---

CHANGELOG.md
solarwinds_apm/version.py

Testrelease 0.18.0.16
Notes:
* Quite a few changes since 0.17.0 I forgot to add to Changelog, so added here
* Testrelease version is high because of several previous publishes used to lambda layer tests
Test traces, still with spaces in span names yay:
* [SWO Django](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/282E6A921A38B0792BC55D28990514C7/F8F5CC5153A62C5F/details/breakdown?perspective=requests&serviceId=e-1655756171056209920&sort_by_breakdown=spanLayer&sort_order_breakdown=ascending)
* [SWO FastAPI](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/CADC48DA1D144830EFF7D7DE76C05E97/B6EEA8A984AEBE22/details/breakdown?perspective=requests&serviceId=e-1655757500269252608&sort_by_breakdown=spanLayer&sort_order_breakdown=ascending) …

NH-65932 Testrelease 0.18.0.X

---

CHANGELOG.md
solarwinds_apm/version.py

Contents for publish and release of APM Python 1.0.0
tox tests pass on this PR... most of them. Still waiting for lint and format check to get an available runner. I expect this to pass [like the last PR for testrelease](https://github.com/solarwinds/apm-python/pull/219) since all .py files the same.
Test traces:
- [SWO Django](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/66892896E7618D901833562D90A488C8/47FD2590CB92A827/details/breakdown?perspective=requests&serviceId=e-1655756171056209920)
- [SWO FastAPI](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/3B62C3B90D94AC0C5592238C56751296/9106B56F0766F012/details/breakdown?perspective=requests&serviceId=e-1655757500269252608)
- [AO Django](https://my.appoptics.com/apm/123092/services/django-app-a-ot/traces/ …

APM Python 1.0.0

---

setup.cfg

Update APM Python package classifiers and metadata because GA, py3.11 has been supported a while, and updated url.

NH-67783 Update APM Python package classifiers and metadata

---

tests/unit/test_configurator/test_configurator_span_processors.py

Add span processor configurator unit tests.

NH-67051 Add span processor config tests

---

tests/unit/test_configurator/conftest.py
tests/unit/test_configurator/test_configurator_init_reporter.py
tests/unit/test_configurator/test_configurator_traces_exporter.py

Adds Reporter configurator function unit tests, with updated fixtures.
At distro startup, it's the upstream `_configure` method that decides if Reporter should be init'd.

NH-67051 Add Reporter config tests

---

tests/unit/test_configurator/conftest.py
tests/unit/test_configurator/test_configurator_configure.py

Add the top-level `configurator._configure` tests, the one called by Otel `instrument` via entry points.

NH-67051 Add the top-level `configurator._configure` tests

---

tests/unit/test_configurator/test_configurator_configure.py
tests/unit/test_configurator/test_configurator_configure_otel.py

Fixes dumb test function signatures, caught by CodeQL in #241: `Normal methods should have 'self', rather than 'mocker', as their first parameter.`

NH-67051 fix dumbness

---

tests/unit/test_apm_config/test_apm_config_get_extension.py
tests/unit/test_sampler/test_sampler.py

Add temporary switches in two unit tests so that they pass while on c-lib <13. I've noted to change these later in https://swicloud.atlassian.net/browse/NH-68264. Doing this under NH-62591 before upstream upgrade to make testing other things easier.

NH-62591 Add temp switches for unit tests while c-lib <13

---

solarwinds_apm/trace/base_metrics_processor.py
solarwinds_apm/trace/inbound_metrics_processor.py
solarwinds_apm/trace/otlp_metrics_processor.py
solarwinds_apm/trace/tnames.py
solarwinds_apm/trace/txnname_calculator_processor.py
tests/unit/test_processors/test_base_metrics_processor.py
tests/unit/test_processors/test_inbound_metrics_processor.py
tests/unit/test_processors/test_otlp_metrics_processor.py
tests/unit/test_processors/test_txnname_calculator_processor.py

Depends on https://github.com/solarwinds/apm-python/pull/254 -- now merged to main.
As per [this PR comment](https://github.com/solarwinds/apm-python/pull/254#discussion_r1428328425), updates the data type of calculated, stored trans_name, url_tran, and custom_name so that it's dot notation instead of indices. We store custom_name separately so that Inbound and OTLP metrics processors can each decide what to do with them (later).

NH-65061 Change processed txn name storage type

---

solarwinds_apm/apm_config.py
solarwinds_apm/trace/otlp_metrics_processor.py
tests/unit/test_apm_config/test_apm_config.py
tests/unit/test_processors/test_otlp_metrics_processor.py

Depends on #255 for name storage type update -- now merged to main
Updates OTLP metrics processor to calculate transaction name for response_time metrics following this order of decreasing precedence:
1. custom SDK name (already stored by `TxnNameCalculatorProcessor`)
2. SW_APM_TRANSACTION_NAME (already stored by `ApmConfig`)
3. AWS_LAMBDA_FUNCTION_NAME (now also stored by `ApmConfig`)
4. automated naming from span name, attributes (already stored by `TxnNameCalculatorProcessor`)

NH-69217 OTLP metrics sw.transaction configurable by env var

---

solarwinds_apm/api/__init__.py
tests/unit/test_api.py

Adds tests for APM Python API methods.
Depends on https://github.com/solarwinds/apm-python/pull/254 because this tests the updated `set_transaction_name` -- now merged to main.

NH-69207 Add API method tests

---

solarwinds_apm/apm_meter_manager.py
solarwinds_apm/configurator.py
solarwinds_apm/sampler.py
tests/integration/test_base_sw_headers_attrs.py
tests/unit/test_apm_meter_manager.py
tests/unit/test_configurator/conftest.py
tests/unit/test_configurator/test_configurator_configure_otel.py
tests/unit/test_configurator/test_configurator_sampler.py
tests/unit/test_sampler/fixtures/sampler.py
tests/unit/test_sampler/test_sampler.py
tests/unit/test_sampler/test_sampler_calculate_attributes.py

Before this change: custom Sampler and MeterManager each init'd their own instances of OboeAPI.
After this change: the Configurator init's one OboeAPI that gets passed to Sampler and MeterManager. I wanted to do this before updating the init call args.

NH-68264 Configurator does the only OboeAPI init

---

.github/dependabot.yml

Updates pip ecosystem groups for Dependabot dependency checks to `otel-core`, `otel-instrumentors`, `otel-utils`, `misc` for PR clarity. Also reverts pip ecosystem checks back to `weekly` so PRs don't happen on weekend.

NH-66478 Update dependabot config

---

solarwinds_apm/trace/otlp_metrics_processor.py
tests/unit/test_processors/test_otlp_metrics_processor.py

Remove `sw.nonce` metrics attribute setting by APM Python, as ingestion does that now.

NH-70994 Remove sw.nonce from metrics attributes

---

solarwinds_apm/apm_noop.py

Fix clib API getTracingDecision no-op function signature, to stop TypeError if lambda and no-op.

NH-70998 Fix no-op function signature

---

solarwinds_apm/configurator.py
tests/unit/test_configurator/test_configurator_metrics_exporter.py

Depends on https://github.com/solarwinds/apm-python/pull/289. EDIT: that's done thanks!
Sets preference for all histograms to report using delta aggregation, including `response_time`.
The entry point `load` is called for any metrics exporters specified by `OTEL_METRICS_EXPORTER`. Otel Python's otlp metrics exporters for [http](https://github.com/open-telemetry/opentelemetry-python/blob/1061d96562990b1c2b596ace87239e7f9616589a/exporter/opentelemetry-exporter-otlp-proto-http/src/opentelemetry/exporter/otlp/proto/http/metric_exporter/__init__.py#L103) and [grpc](https://github.com/open-telemetry/opentelemetry-python/blob/1061d96562990b1c2b596ace87239e7f9616589a/exporter/opentelemetry-exporter-otlp-proto-grpc/src/opentelemetry/exporter/otlp/proto/grpc/metric_exporter/__init__.py#L101) both …

NH-70998 Set histogram preferred temporality delta

---

solarwinds_apm/apm_meter_manager.py
solarwinds_apm/apm_noop.py
tests/unit/test_apm_meter_manager.py

As per spec update, removes the OTLP meters (regular and no-op) that report `trace.service.sample_rate` and `trace.service.sample_source`.
Keeps the API no-op methods since extension still has them.

NH-72055 Remove meters for sample_rate, sample_source

---

solarwinds_apm/configurator.py
tests/unit/test_configurator/test_configurator_metrics_exporter.py

We init [PeriodicExportingMetricReader](https://github.com/open-telemetry/opentelemetry-python/blob/1061d96562990b1c2b596ace87239e7f9616589a/opentelemetry-sdk/src/opentelemetry/sdk/metrics/_internal/export/__init__.py#L420-L428) with export interval infinity so reading is no longer periodic.

NH-70998 PeriodicExportingMetricReader with export_interval infinity

---

solarwinds_apm/apm_meter_manager.py

Cosmetic change to rename ObservableGauge callback functions' local variables. Just for clarity, and noticed these after the c-lib 14.0.2 update.
Does not change for the sample_rate/source callbacks because they'll be removed in https://github.com/solarwinds/apm-python/pull/299

NH-70998 Rename Gauge callback local variables

---

solarwinds_apm/trace/base_metrics_processor.py
solarwinds_apm/trace/inbound_metrics_processor.py
solarwinds_apm/trace/otlp_metrics_processor.py
tests/unit/test_processors/test_base_metrics_processor.py

Fixes OTLP response_time metrics so they're reported in milliseconds (not nanoseconds, as before).
Here is a test otelcol metrics message following a request to a route with a `time.sleep(3)` included:
```
Metric #0
Descriptor:
-> Name: trace.service.response_time
-> Description: measures the duration of an inbound HTTP request
-> Unit: ms
-> DataType: Histogram
-> AggregationTemporality: Cumulative
HistogramDataPoints #0
Data point attributes:
-> sw.is_error: Str(false)
-> http.status_code: Int(200)
-> http.method: Str(GET)
-> sw.transaction: Str(unused)
StartTimestamp: 2024-02-01 18:28:18.418123297 +0000 UTC
Timestamp: 2024-02-01 18:28:18.420461838 +0000 UTC
Count: 1
Sum: 3017.000000
Min: 3017.000000
Max: 3017.000000
```

NH-70998 OTLP response_time metrics in milliseconds

---

.github/workflows/build_publish_lambda_layer_aarch64.yaml
.github/workflows/build_publish_pypi_and_draft_release.yaml
.github/workflows/build_publish_testpypi.yaml
.github/workflows/verify_install.yaml

Upgrade [getsentry/action-github-app-token](https://github.com/getsentry/action-github-app-token) to [v3](https://github.com/getsentry/action-github-app-token/releases/tag/v3.0.0) which updates to use Node 20.
Test run of Verify Installation workflow: https://github.com/solarwinds/apm-python/actions/runs/7875245332. There are only Node 16 warnings for the Ubuntu 18 tests which we're keeping for now.

NH-71963 Upgrade getsentry token action

---

lambda/requirements.txt
solarwinds_apm/apm_constants.py
solarwinds_apm/configurator.py
solarwinds_apm/distro.py
tests/unit/test_distro.py

Before this PR, metrics and traces exporter defaults depended on is_lambda (see https://github.com/solarwinds/apm-python/pull/217).
After this PR, the defaults don't depend on lambda. They instead depend on `OTEL_EXPORTER_OTLP_PROTOCOL` which we require for otlp exporting in any environment.
If Protocol is `http/protobuf`:
1. `OTEL_METRICS_EXPORTER` defaults to otlp_proto_http
2. `OTEL_TRACES_EXPORTER` defaults to otlp_proto_http
If Protocol is `grpc`:
1. `OTEL_METRICS_EXPORTER` defaults to otlp_proto_grpc
2. `OTEL_TRACES_EXPORTER` defaults to otlp_proto_grpc
If Protocol is anything else or unset:
1. No default for `OTEL_METRICS_EXPORTER`. User must configure metrics exporters else none will initialize.
2. `OTEL_TRACES_EXPORTER` defaults to solarwinds_exporter
Note that the above are for …

NH-66126 Exporter defaults based on configured protocol

---

solarwinds_apm/trace/otlp_metrics_processor.py
tests/unit/test_processors/test_otlp_metrics_processor.py

`http.*` attributes are set on metrics if they weren't empty on the span at on_end.

NH-73037 http.* attributes set on metrics it not empty

---

solarwinds_apm/apm_logging.py

Adds formatter to RotatingFileHandler so that logs in contents of `SW_APM_LOG_FILEPATH` match what the StreamHandler already does. Example logs
```
2024-02-21 17:04:46,652 [ solarwinds_apm.configurator WARNING  p#1.281472885620768] Agent disabled. Not sending init message.
2024-02-21 17:04:49,552 [ solarwinds_apm.api DEBUG    p#1.281472856486304] Cannot cache custom transaction name abc because agent not enabled; ignoring
```

NH-70772 Add formatter to rotatingfilehandler

---

solarwinds_apm/trace/otlp_metrics_processor.py
tests/unit/test_processors/test_otlp_metrics_processor.py

`sw.is_error` attribute on response_time metrics uses boolean values instead of string.
See also [comment](https://swicloud.atlassian.net/browse/NH-73037?focusedCommentId=2626890).

NH-73037 sw.is_error attribute as boolean

---

.github/workflows/build_publish_lambda_layer_aarch64.yaml
.github/workflows/build_publish_pypi_and_draft_release.yaml
.github/workflows/build_publish_testpypi.yaml
.github/workflows/verify_install.yaml

Workflows use new `EC2_RUNNER_ARN` instead of old key combo.
Tested by running [smoke test](https://github.com/solarwinds/apm-python/actions/runs/8084999471/job/22091576851) workflow and [layer publish](https://github.com/solarwinds/apm-python/actions/runs/8085062667) workflow which were both successful.

NH-74059 Use EC2_RUNNER_ARN

---

Makefile
lambda/requirements-so.txt

Fixes grpcio module `ImportError` if layer run outside Python 3.8. See [comment](https://swicloud.atlassian.net/browse/NH-70758?focusedCommentId=2634819) for testing.

NH-70758 Fix grpcio ImportError if outside py38

---

solarwinds_apm/distro.py

Updates custom distro `load_instrumentor` method to catch and log errors at auto-instrumentation, such as `grpcio` ImportError when the wrong distro for a particular architecture is used (e.g. `arm64` instead of `x86_64`). Example output, instead of a multi-line stacktrace:
> `2024-03-05 17:58:41,108 [ solarwinds_apm.distro ERROR p#17.140002353669952] Could not load instrumentor grpc_aio_client: cannot import name 'cygrpc' from 'grpc._cython' (/opt/python/grpc/_cython/__init__.py)`

NH-74450 Custom distro load_instrumentor catches and logs

---

lambda/solarwinds-apm/wrapper

Disable AWS context propagation by default by setting `true` with other env vars in wrapper script.

NH-71085 Disable AWS context propagation by default

---

solarwinds_apm/configurator.py
tests/unit/test_configurator/conftest.py
tests/unit/test_configurator/test_configurator_configure.py
tests/unit/test_configurator/test_configurator_create_init_event.py
tests/unit/test_configurator/test_configurator_report_init_event.py

Splits the creation vs report of the c-lib Reporter init event (outside lambda, all at startup). Also logs at `info` level the resulting send status of `True` or `False`. Most of the changes are unit tests from renaming a method.

NH-68251 Split create/report init event and log status

---

.github/workflows/build_publish_lambda_layer.yaml
.github/workflows/build_publish_lambda_layer_aarch64.yaml
.github/workflows/build_publish_lambda_layer_x86_64.yaml
.github/workflows/publish_lambda_layer.yaml

Adds lambda production publish workflow by adding a new `publish-dest` input param to the existing workflow for staging. The input determines whether we use the existing staging publish role or the new role for prod. I've also renamed the reused workflows to make it a bit more clear which one is for dispatch: `Publish APM Python lambda layer`.
Tested [production publish](https://github.com/solarwinds/apm-python/actions/runs/8381326109) resulting in layers ending in `1_6_0_2:1`. Tested [staging publish](https://github.com/solarwinds/apm-python/actions/runs/8381120357) resulting in layers ending in `1_6_0_2:2`. I did these on [another PR](https://github.com/solarwinds/apm-python/pull/340) for the custom build branch and this PR ports over those changes for `main`.

NH-75964 Add lambda production publish workflow

---

solarwinds_apm/configurator.py
tests/unit/test_configurator/test_configurator_configure.py

Stops logging this all the time in lambda:
> `2024-03-25 20:17:11,179 [ solarwinds_apm.configurator ERROR p#18.548324724752] There was an issue with generating the reporter init message.`
Instead, if debug level high, we see this instead:
> `2024-03-26 00:38:38,503 [ solarwinds_apm.configurator DEBUG    p#16.140177044481856] No init event in lambda`
See ticket comment for testing. The unit tests weren't set up properly so I had to make them over too.

NH-76217 Fix init event logging

---

Makefile
lambda/check_lambda_modules.sh

Adds check_lambda_modules script as part of "Publish APM Python lambda layer" gh workflow and local builds. See ticket comment for details/rationale.
This duplicates what is already on the `custom` lambda build branch, with last successful staging run here: https://github.com/solarwinds/apm-python/actions/runs/8456345539 including logs:
> `Checking installed lambda files and modules`
> `Successfully verified lambda files and modules for layer archive`
This PR is to add the call to check_lambda_modules to "normal" lambda builds when upstream is upgraded.

NH-76401 Add check_lambda_modules before layer publish

---

solarwinds_apm/apm_logging.py
tests/unit/test_apm_config/test_apm_config.py

Fixes APM log duplication that was happening in these different scenarios:
1. instrumented app code (user side) calls [logging.basicConfig](https://docs.python.org/3/library/logging.html#logging.basicConfig)
2. `OTEL_PYTHON_LOG_CORRELATION` enabled (in and out of lambda), because LoggingInstrumentor [also calls logging.basicConfig](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/fdcbbddb6c753e5e9d494ba399a5b4bcab4afc3f/instrumentation/opentelemetry-instrumentation-logging/src/opentelemetry/instrumentation/logging/__init__.py#L147)
3. `OTEL_PYTHON_LOG_CORRELATION` enabled and `SW_APM_LOG_FILEPATH` set

NH-75342 Loggers stop logging handler propagation

---

solarwinds_apm/sampler.py
tests/unit/test_sampler/test_sampler.py
tests/unit/test_sampler/test_sampler_calculate_attributes.py

Updates APM Python sampler to map c-lib decision to Otel decision once per `should_sample`, instead of twice which makes logs a bit misleading.

NH-77561 Map c-lib to Otel decision once

---

solarwinds_apm/exporter.py
solarwinds_apm/w3c_transformer.py

Removes a debug line from early development of APM Python that I would argue is no longer useful and is misleading because it's logged twice by custom exporter and response propagator for one span. Example:
> `2024-04-30 16:18:18,592 [ solarwinds_apm.w3c_transformer DEBUG    p#1.281472921751584] Generated traceparent 00-b9675c6c50a9331392aad6fa3f6a3512-32c0d62f1ef75148-01 from SpanContext(trace_id=0xb9675c6c50a9331392aad6fa3f6a3512, span_id=0x32c0d62f1ef75148, trace_flags=0x01, trace_state=[], is_remote=False)`
Without that, we can still debug with these logs:
1. Sampling decision is logged with `Got liboboe decision outputs`.
2. trace_id/span_id for APM-proto export is logged with `Start a new trace` or `Continue trace from`.
3. If it's an instrumented http service, use `curl -v` and …

NH-77561 Remove early dev debug line

---

solarwinds_apm/configurator.py
solarwinds_apm/sampler.py
tests/integration/test_base_sw_headers_attrs.py
tests/unit/test_configurator/test_configurator_sampler.py
tests/unit/test_sampler/fixtures/sampler.py
tests/unit/test_sampler/test_sampler.py
tests/unit/test_sampler/test_sampler_calculate_attributes.py
tests/unit/test_sampler/test_sampler_calculate_otlp_tname.py

Sampler inits with Reporter to keep it alive after Configuration, else it dies if `solarwinds_exporter` not set and sampling don't work.

NH-80234 Sampler inits with Reporter

---

solarwinds_apm/distro.py
tests/unit/test_distro.py

Updates the startup case for logging a warning to logging an error if using Python 3.7, which neither APM Python nor OTel Python supports now.
APM Python will still continue to (try to) configure Otel and the SDK will run.
Is this too strong, or not strong enough?

NH-79315 Update log warning to error if Python 3.7

---

solarwinds_apm/sampler.py
solarwinds_apm/semconv/trace/__init__.py
tests/unit/test_sampler/test_sampler_calculate_tracing_mode.py
tests/unit/test_semconv/__init__.py
tests/unit/test_semconv/test_trace.py

Adds new "semconv helper" to collect url-related span attributes by order of precedence: new HTTP semconv > old HTTP semconv > None. This is to continue to support tracing mode per-request, if configured.

NH-81797 Add get_url_attrs from new or old semconv

---

pyproject.toml

Fixes builds (testpypi and lambda) that were failing because package wasn't including new internal APM semconv.trace module.

NH-82784 Fix builds

---

docker-compose.yml
tests/docker/install/docker-compose.yml

Removes docker-compose `version` key because now warned as obsolete (see [dc spec](https://github.com/compose-spec/compose-spec/blob/master/spec.md#version-and-name-top-level-elements)).

NH-82791 Remove deprecated docker-compose `version`

---

solarwinds_apm/propagator.py
tests/unit/test_propagator.py

In SW propagator `inject` method for outgoing requests, do not re-inject `baggage` header if value is empty, i.e. if `"baggage": ""`
I think technically `"baggage": ""` is allowed according to HTTP [RFC 7230 section 3.2](https://datatracker.ietf.org/doc/html/rfc7230#section-3.2) where
> `field-value    = *( field-content / obs-fold )`
and 
> HTTP does not place a predefined limit on the length of each header field or on the length of the header section as a whole
The [W3C Candidate Recommendation for Baggage](https://www.w3.org/TR/baggage/) does not explicitly mention a separate header length requirement.
For the [W3C Recommendation for tracestate](https://www.w3.org/TR/trace-context/#tracestate-header-field-values), it says this, which is not for Baggage but seems like a good guide for …

NH-82238 Don't inject baggage header if empty

---

solarwinds_apm/apm_config.py
tests/unit/test_apm_config/test_apm_config.py

Ignores `SW_APM_EXPORT_LOGS_ENABLED` / `exportLogsEnabled` if collector is AO, then sets internally to `False`. Customer can still manually configure OTLP logs export with `OTEL_*` env vars that take precedence (see https://github.com/solarwinds/apm-python/pull/393).

NH-80452 Ignore export logs config when AO collector

---

lambda/solarwinds-apm/wrapper
solarwinds_apm/configurator.py
solarwinds_apm/distro.py
tests/unit/test_configurator/conftest.py
tests/unit/test_configurator/test_configurator_logs_exporter.py

Adjusts APM Python to support OTLP logs processing and export while in lambda.
Had to switch to always init `BatchLogRecordProcessor` because `SimpleLogRecordProcessor` keeps timing out, plus I will be changing the metrics processor like this soon too. Updates the lambda wrapper to set a different default collector endpoint for logs.
See ticket comment for manual testing.

NH-80452 Add OTLP logs export from lambda

---

CHANGELOG.md

Contents used to testrelease APM Python 2.2.0.4
Released to TestPyPI at: https://test.pypi.org/project/solarwinds-apm/2.2.0.4/
Smoke/Install tests pass: https://github.com/solarwinds/apm-python/actions/runs/10292779610
See ticket comment for manual test results.

NH-87573 Testrelease 2.2.0.4

---

.github/workflows/run_tox_lint_format.yaml
CONTRIBUTING.md
solarwinds_apm/propagator.py
solarwinds_apm/response_propagator.py
solarwinds_apm/sampler.py
solarwinds_apm/trace/serviceentry_processor.py
tox.ini

Update linting to run on all supported Python versions.
Lints some code to meet Python 3.12 recommendations, with `from __future__` import so Python 3.8, 3.9 still work.
Example GH workflow run: https://github.com/solarwinds/apm-python/actions/runs/10727514035
Local command is slightly different: `make tox OPTIONS="-e lint"` is now `make tox OPTIONS="-e py312 lint"` etc

NH-90488 lint for all supported Python versions

---

.pylintrc_py38
docker-compose.yml
scripts/lint_and_format.py
solarwinds_apm/apm_config.py
solarwinds_apm/apm_fwkv_manager.py
solarwinds_apm/apm_txname_manager.py
solarwinds_apm/configurator.py
solarwinds_apm/sampler.py

[pylint 3.3.0](https://github.com/pylint-dev/pylint/releases/tag/v3.3.0) came out last Friday and APM Python always uses latest. Fixes issues or update `ignore` statements.
Splitting `.pylintrc` files until Python 3.8 support is dropped because pylint 3.3.0 Requires-Python >=3.9.0
Also adds some `pip install` longer timeouts to build container (top docker-compose) for when downloads are slow 💀

NH-92062 Lint existing code for pylint 3.0.0 upgrade

---

solarwinds_apm/distro.py
tests/unit/test_distro.py

Adds support for individual sqlcommenter enabling with new env var, `SW_APM_ENABLED_SQLCOMMENT`. It should be a comma-separated string of KVs paired by equals signs, where key is one of the known instrumentor names and value is a case-insensitive "boolean" string. Example: `SW_APM_ENABLED_SQLCOMMENT='django=true,sqlalchemy=false'`. False is the default, so isn't necessary to set.
Deprecates the env var `OTEL_SQLCOMMENTER_ENABLED` (documented [here](https://documentation.solarwinds.com/en/success_center/observability/content/configure/services/python/configure.htm#trace-queries)) for all-or-none enabling of sqlcommenting by instrumentors, via [this warning log](https://github.com/solarwinds/apm-python/blob/a175028cfa3ddcb695d312b23b0e70a82f63f462/solarwinds_apm/distro.py#L226-L228). There …

NH-92060 Add support for individual sqlcommenter enabling; deprecate all-or-none

---

solarwinds_apm/distro.py
tests/unit/test_distro.py

Noticed a small inconvenience while updating docs. This change allows case-insensitive instrumentor names when enabling sqlcomment via `SW_APM_ENABLED_SQLCOMMENT`.

NH-92060 Allow case-insensitive instrumentor names when enabling sqlcomment

---

.github/workflows/codeql_analysis.yml

Removes CodeQL deprecated `setup-python-dependencies` input to stop this warning at workflow runs:
> The setup-python-dependencies input is deprecated and no longer has any effect. We recommend removing any references from your workflows. See https://github.blog/changelog/2024-01-23-codeql-2-16-python-dependency-installation-disabled-new-queries-and-bug-fixes/ for more information.
Example run, now without warning: https://github.com/solarwinds/apm-python/actions/runs/11673881050

NH-95071 Remove CodeQL deprecated setup-python-dependencies input

---

setup.py
tests/docker/install/client.py
tests/unit/test_apm_config/test_apm_config_get_extension.py
tests/unit/test_configurator/fixtures/resource.py
tests/unit/test_configurator/fixtures/trace.py
tests/unit/test_configurator/test_configurator_metrics_exporter.py
tests/unit/test_configurator/test_configurator_sampler.py
tests/unit/test_exporter.py
tests/unit/test_processors/test_inbound_metrics_processor.py
tests/unit/test_processors/test_otlp_metrics_processor.py
tests/unit/test_propagator.py
tests/unit/test_response_propagator.py
tests/unit/test_sampler/fixtures/parent_span_context.py
tests/unit/test_xtraceoptions.py

Much-needed scrub. Addresses these old CodeQL notes and warnings, one under a build helper and the rest under tests:
1. https://github.com/solarwinds/apm-python/security/code-scanning/2
2. https://github.com/solarwinds/apm-python/security/code-scanning/51
3. https://github.com/solarwinds/apm-python/security/code-scanning/52
4. https://github.com/solarwinds/apm-python/security/code-scanning/1
5. https://github.com/solarwinds/apm-python/security/code-scanning/281
6. https://github.com/solarwinds/apm-python/security/code-scanning/241
7. https://github.com/solarwinds/apm-python/security/code-scanning/39
8. https://github.com/solarwinds/apm-python/security/code-scanning/40
9. https://github.com/solarwinds/apm-python/security/code-scanning/113
10. …

NH-95072 Address CodeQL notes, warnings

---

solarwinds_apm/apm_config.py
solarwinds_apm/configurator.py
solarwinds_apm/distro.py
solarwinds_apm/exporter.py
tests/integration/test_base_sw_headers_attrs.py
tests/unit/test_apm_config/test_apm_config.py
tests/unit/test_apm_config/test_apm_config_agent_enabled.py
tests/unit/test_configurator/test_configurator_add_all_instrumented_versions.py
tests/unit/test_configurator/test_configurator_logs_exporter.py
tests/unit/test_configurator/test_configurator_metrics_exporter.py
tests/unit/test_configurator/test_configurator_propagators.py
tests/unit/test_configurator/test_configurator_sampler.py
tests/unit/test_configurator/test_configurator_traces_exporter.py
tests/unit/test_exporter.py

pkg_resource is [deprecated](https://setuptools.pypa.io/en/latest/pkg_resources.html#package-discovery-and-resource-access-using-pkg-resources). Replaces pkg_resource uses with an Otel Python util to map importlib depending on Python version.
Replaces https://github.com/solarwinds/apm-python/pull/429 following release of Otel Python 1.28.1/0.49b1. Being merged into https://github.com/solarwinds/apm-python/pull/450, not main, to get tests to pass.

NH-63282 Remove pkg_resources usage

---

.github/dependabot.yml

Change the new `/lambda/tests` deps Dependabot check to weekly. It looks like [it works](https://github.com/solarwinds/apm-python/actions/runs/11978203976/job/33397733401) and should be done weekly with all the other checks now.

NH-96758 Change /lambda/tests deps check to weekly

---

dev-requirements.txt

Flask 3.1 came out this month. It drops Python 3.8 support! https://flask.palletsprojects.com/en/stable/changes/
Runs APM Python tox tests with Flask 3.1, except Python 3.8 which sticks to Flask 3.0. See ticket for manual testing with Flask 3.1.
A user trying to install Flask 3.1 on Python <=3.8 will see pip install errors early before instrumentation is attempted.

NH-96831 Run tox tests with Flask 3.1, except Python 3.8

---

solarwinds_apm/configurator.py

Changes version lookup issue logs from `warning` to `debug`. My argument is that they are currently misleading when in Lambda or k8s operator, which both manually pre-install as many instrumentors as possible instead of bootstrapping only what's needed based on frameworks installed in the current environment. If there is conflict that actually prevents instrumentation, it [will be logged by upstream](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/ec3c51dcd18fa747c567708d8aead21cd9081dca/opentelemetry-instrumentation/src/opentelemetry/instrumentation/dependencies.py#L72-L76). Meanwhile the logs should still be kept if there are reporter init event issues that need deeper investigation. See ticket description for more details. Let me know what you think 😺

NH-100215 Update init event version lookup logs

---

solarwinds_apm/distro.py
tests/unit/test_distro.py

Simplifies APM Python custom distro by removing one unnecessary `is_lambda` check.
Change is that now, in lambda environment, default values for `OTEL_EXPORTER_OTLP_(TRACES|METRICS|LOGS)_HEADERS` always get set to `f"authorization=Bearer%20{header_token}"` even if `header_token` is empty, which should normally be the case. This does not affect export to otel-collector layer on localhost -- see ticket comment for more test info. This is again for default values, so user can always override with their own `HEADERS` set in environment.
Works the same as before outside of lambda.
Also adds more unit tests and clarifies existing ones.

NH-100646 Default OTLP auth header always in lambda

---

solarwinds_apm/apm_config.py
tests/unit/test_apm_config/test_apm_config.py

Changes APM-internal service_key updates to be more general. Removes is_lambda check so that `_update_service_key_name` is always called. Updates that function to avoid `IndexError` for cases like when in Lambda and `SW_APM_SERVICE_KEY` is unnecessarily set as a weird value. Adds missing test coverage.

NH-100646 Internal service_key updates more general

---

solarwinds_apm/apm_config.py
tests/unit/test_apm_config/test_apm_config_is_legacy.py

Note: this will merge into epic feature branch `NH-79025-otlp-by-default`.
Adds first parts for APM Python to support `SW_APM_LEGACY` by reading from environment variable (highest precedence) or `legacy` in JSON config file, else default `False`. APM Python does not use this for anything yet.
Why are `calculate_is_legacy` and now `get_cnf_dict` classmethods in ApmConfig? Because:
1. Distro needs them to change its `setdefault` calls in a future PR
2. Distro and Configurator can't share one ApmConfig due to lifecycles when [sitecustomize](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/748c92592d2f476199667629defce4a3bca9ecc9/opentelemetry-instrumentation/src/opentelemetry/instrumentation/auto_instrumentation/sitecustomize.py#L37-L39) is used for auto-instrumentation. …

NH-98561 Add ApmConfig.calculate_is_legacy

---

.github/workflows/build_publish_image_autoinstrumentation.yaml
image/requirements-nodeps.txt

Adds Docker Scout cves scan to build-publish workflow. Example run with summary: https://github.com/solarwinds/apm-python/actions/runs/13000262293

NH-100298 Add docker scout cves for autoinstrumentation-python

---

solarwinds_apm/apm_config.py
tests/unit/test_apm_config/fixtures/cnf_dict.py
tests/unit/test_apm_config/test_apm_config.py
tests/unit/test_apm_config/test_apm_config_cnf_file.py

Note: this will merge into epic feature branch `NH-79025-otlp-by-default`.
Adds ApmConfig support for reading `SW_APM_LEGACY` env var and `legacy` in JSON config file. Default is `False`. Just stores the value internally for now.
This is needed for future PRs to e.g. decide when to init components like Reporter and InboundMetricsSpanProcessor. This is similar to https://github.com/solarwinds/apm-python/pull/497 but to make the value available internally to the Configurator and the rest of APM's life cycle (see also [sitecustomize](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/748c92592d2f476199667629defce4a3bca9ecc9/opentelemetry-instrumentation/src/opentelemetry/instrumentation/auto_instrumentation/sitecustomize.py#L37-L39) used for auto-instrumentation).

NH-98561 Add ApmConfig support for SW_APM_LEGACY

---

tests/unit/test_apm_config/test_apm_config.py
tests/unit/test_apm_config/test_apm_config_agent_enabled.py
tests/unit/test_apm_config/test_apm_config_cnf_file.py
tests/unit/test_apm_config/test_apm_config_service_name.py

If we run all tox tests at once, e.g. `make tox OPTIONS="-e py312-nh-staging"`, then all tests pass. But if we only run the ApmConfig unit tests, e.g.
`make tox OPTIONS="-e py312-nh-staging -- tests/unit/test_apm_config/*"`
Then there are 27 failures!! The ApmConfig tests themselves are not setting their conditions up properly. This fixes the `os.environ` mocking using an existing fixture.

NH-100961 Fix ApmConfig unit test conditions

---

solarwinds_apm/distro.py
tests/unit/test_distro.py

Note: This will merge into epic feature branch `NH-79205-otlp-by-default`.
This updates APM Python's `Distro` component, which is called first when [sitecustomize](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/748c92592d2f476199667629defce4a3bca9ecc9/opentelemetry-instrumentation/src/opentelemetry/instrumentation/auto_instrumentation/sitecustomize.py#L37-L39) is used for auto-instrumentation, to more clearly prepare for OTLP-by-default. I'm changing the parts used to `setdefault` of exporter configurations. All values can still be configured (i.e. override defaults) by user via `OTEL_*` env vars. It is the `Configurator` component's responsibility to load and init the exporters later according to final config.
Key code changes:
(1)
For users, it used to be that …

NH-98561 Update OTLP setdefaults with legacy check and cleanup

---

tests/integration/test_base_sw_headers_attrs.py

Note: This will merge into epic feature branch NH-79205-otlp-by-default.
Preps the APM Python integration tests to all run in legacy mode, plus a small fix to restore empty `SW_APM_SERVICE_KEY` before the unit tests run. This currently isn't an issue but the bug is revealed as I write more updates and tests 😃

NH-79205 Prep integration tests to run as legacy, plus small fix

---

solarwinds_apm/apm_config.py
tests/unit/test_apm_config/test_apm_config.py
tests/unit/test_apm_config/test_apm_config_agent_enabled.py
tests/unit/test_apm_config/test_apm_config_cnf_file.py
tests/unit/test_apm_config/test_apm_config_get_extension.py

Note: This will merge into epic feature branch `NH-79205-otlp-by-default`
`_get_extension_components` is now based on `SW_APM_LEGACY` false/true, instead of "is lambda". I'm keeping two separate try-except for now around import of `solarwinds_apm.extension.oboe` then import of OboeAPI and options, in case of upcoming updated extension builds. Also updates `str(ApmConfig)` debug helper to include OboeAPI.

NH-100646 _get_extension now based on if Legacy, not if Lambda

---

solarwinds_apm/configurator.py
tests/unit/test_configurator/conftest.py
tests/unit/test_configurator/test_configurator_configure_otel.py
tests/unit/test_configurator/test_configurator_metrics_exporter.py
tests/unit/test_configurator/test_configurator_sampler.py

Note: This will merge into epic feature branch `NH-79205-otlp-by-default`
This makes initialization of custom OTel components explicitly dependent on Legacy Mode (`SW_APM_LEGACY`) within `_configure_otel_components`. The implicit dependency on supported env vars like `OTEL_METRICS_EXPORTER` still exists in the helper functions to keep supporting upstream config options. But now there is a clear line at 'top level' for internal component setup. Traces exporter is always configured with either default values set by SolarWindsDistro or user-set `OTEL_TRACES_EXPORTER`.
This also centralizes agent enabled vs disabled behaviour into `_configure_otel_components`, rather than having some but not all of the helpers doing it (probably some code smell).

NH-98561 Update configure_otel_components conditions

---

lambda/solarwinds-apm/wrapper

Note: This will merge into epic feature branch `NH-79205-otlp-by-default`.
Removes default configs set by the wrapper for APM Python Lambda layers because no longer necessary, as these are now the defaults outside Lambda too (see https://github.com/solarwinds/apm-python/pull/499, https://github.com/solarwinds/apm-python/pull/508).

NH-98561 Remove unnecessary Lambda-specific defaults

---

solarwinds_apm/sampler.py
tests/unit/test_sampler/fixtures/sampler.py
tests/unit/test_sampler/test_sampler.py

Note: This will merge into epic feature branch `NH-79205-otlp-by-default`.
Updates Sampler to use Context for decision-making if legacy, else use OboeAPI.

NH-98561 Sampler uses Context if legacy, else OboeAPI

---

solarwinds_apm/apm_config.py

Prevent AttributeError if OTEL_PROPAGATORS is None, which could happen if if user sets `OTEL_PYTHON_DISTRO` to something that is not `solarwinds_distro` while using `OTEL_PYTHON_CONFIGURATOR=solarwinds_configurator`.
This will still log and agent_enabled will be False a few lines down, so this change doesn't silence anything:
```
logger.error(
"Must include tracecontext and solarwinds_propagator in OTEL_PROPAGATORS to use SolarWinds APM. Tracing disabled."
)
return False
```

NH-100958 Prevent AttributeError if OTEL_PROPAGATORS is None

---

solarwinds_apm/apm_config.py
solarwinds_apm/configurator.py
solarwinds_apm/distro.py
solarwinds_apm/trace/otlp_metrics_processor.py
tests/unit/test_apm_config/test_apm_config.py
tests/unit/test_apm_config/test_apm_config_calculate_logs_enabled.py
tests/unit/test_apm_config/test_apm_config_calculate_metrics_enabled.py
tests/unit/test_apm_config/test_apm_config_is_legacy.py
tests/unit/test_configurator/conftest.py
tests/unit/test_configurator/test_configurator_configure_otel.py
tests/unit/test_configurator/test_configurator_logs_exporter.py
tests/unit/test_configurator/test_configurator_metrics_exporter.py
tests/unit/test_configurator/test_configurator_span_processors.py
tests/unit/test_distro.py

Note: This will merge into epic feature branch `NH-79205-otlp-by-default`.
Before these changes, `SW_APM_EXPORT_(METRICS|LOGS)_ENABLED` was a convenience config for enabling/disabling all metrics and logs export by OTLP unless AO collector set. But now we can and will support both an AO collector and an OTLP collector.
This PR changes the role of `SW_APM_EXPORT_(METRICS|LOGS)_ENABLED` (breaking!) to support these cases:
If `SW_APM_LEGACY=true` and `SW_APM_EXPORT_(METRICS|LOGS)_ENABLED=true`, then library still exports SWO metrics by APM-proto. In addition, Otel Python instrumentor metrics and logs will export by OTLP. If `ENABLED=false` (default), then only do SWO metrics by APM-proto.
If not legacy and `SW_APM_EXPORT_(METRICS|LOGS)_ENABLED=false`, then library still exports SWO metrics …

NH-98561 Breaking: Update metrics/logs-from-OTel opt-in and existing config

---

image/requirements.txt

Adds upper limit to `urllib3` for operator autoinstrumentation image builds to maintain Python 3.8 support. [Python OTLP HTTP exporter](https://github.com/open-telemetry/opentelemetry-operator/blob/main/autoinstrumentation/python/requirements.txt#L4) depends on [requests ~= 2.7](https://github.com/open-telemetry/opentelemetry-python/blob/main/exporter/opentelemetry-exporter-otlp-proto-http/pyproject.toml#L37) and that depends on ["urllib3>=1.21.1,<3"](https://github.com/psf/requests/blob/main/setup.py#L39). [urllib 2.3.0](https://github.com/urllib3/urllib3/releases/tag/2.3.0) is the latest and drops support of Python 3.8.

NH-101919 Add upper limit to urllib3 for operator builds

---

solarwinds_apm/distro.py
tests/unit/test_distro.py

Removes last support of proprietary `OTEL_SQLCOMMENTER_ENABLED` and `OTEL_SQLCOMMENTER_OPTIONS`. They have been deprecated since APM Python 3.1.0 (October 1, 2024) and a warning was being logged.

NH-92496 Remove deprecated config support

---

image/requirements.txt

Add ClickInstrumentor to image build now that we've upgraded Otel Python.

NH-102113 Add ClickInstrumentor to image build

---

solarwinds_apm/configurator.py
solarwinds_apm/distro.py
tests/unit/test_configurator/conftest.py
tests/unit/test_configurator/test_configurator_configure_otel.py
tests/unit/test_configurator/test_configurator_logs_exporter.py
tests/unit/test_distro.py

Note: this will merge into feature branch `NH-79205-otlp-by-default`.
Updates APM Python support of `OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED`:
1. `OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED` is False by default; it's an opt-in for users.
2. If True, then logs SDK handler is created and added.
3. Logging provider and exporters are always set up, with latter depending on `OTEL_LOGS_EXPORTER` (otlp http by default).

NH-98561 Update logging auto-instrumentation support

---

solarwinds_apm/distro.py
tests/unit/test_distro.py

Add support for new config `SW_APM_ENABLED_SQLCOMMENT_ATTRIBUTE`. It is "true" by default for APM Python for all instrumentors. It can be set to "false" for each to opt out. When true _and_ `SW_APM_ENABLED_SQLCOMMENT` is true for that instrumentor, then it will add sqlcomment to `db.statement` attribute.
It accepts a string representing a list of instrumentor keys and their values, delimited by commas. Accepted instrumentor names are: sqlalchemy, django, flask, psycopg2, and psycopg2. Other keys will be ignored.
Example:
```
export SW_APM_ENABLED_SQLCOMMENT_ATTRIBUTE="psycopg2=true,sqlalchemy=false"
```

NH-102114 Add support for SW_APM_ENABLED_SQLCOMMENT_ATTRIBUTE

---

.github/scripts/release_pr.sh

Updates the "Create Release PR" workflow to also bump the APM Python version in [image/requirements-nodeps.txt](https://github.com/solarwinds/apm-python/blob/main/image/requirements-nodeps.txt#L1). This is so "Publish APM Python Auto-Instrumentation" can be run, manually and minutes after PyPI updates are picked up by GH, after PyPI publish is complete but with less to remember.
This also fixes the existing [version.py](https://github.com/solarwinds/apm-python/blob/main/solarwinds_apm/version.py#L1) update logic that was unnecessarily adding newlines.
Example test PR: https://github.com/solarwinds/apm-python/pull/533

NH-102271 Add image APM version bump to 'Create Release PR' action

---

.github/workflows/build_publish_image_autoinstrumentation.yaml

Replaces https://github.com/solarwinds/apm-python/pull/530
Docker scout scan results more consistent like APM Java. Splits image build with first load=true, and removes fs scan. Adds upload of sarif results. See ticket comment for result.

NH-102374 update scout scans

---

.github/workflows/build_publish_image_autoinstrumentation.yaml

Remove "push" condition for GH logins during image build, which is currently causing `401 Unauthorized`. [Example failed workflow](https://github.com/solarwinds/apm-python/actions/runs/13599288367/job/38022561971). Currently we run this through manual trigger, not on-push.

NH-103097 Remove image build "push" condition for GH logins

---

solarwinds_apm/exporter.py
tests/unit/test_exporter.py

This is to stop the warning reported in https://github.com/solarwinds/apm-python/issues/538: `2025-03-03 10:53:22,630 [ solarwinds_apm.exporter WARNING p#2669645.138014233724608] Version lookup of boto3sqs failed, so skipping: No module named 'boto3sqs'`
APM Python custom exporter does lookups of instrumentation frameworks to enrich exported spans. The instrumentation package `opentelemetry.instrumentation.boto3sqs` is for [entrypoint boto3](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/d5dce5de996efcf2c2f85eed787c13f831095377/instrumentation/opentelemetry-instrumentation-boto3sqs/pyproject.toml#L41), the latter being the actual name of the module.

NH-103629 Update APM exporter's lookup of boto3

---

solarwinds_apm/propagator.py
tests/unit/test_propagator.py

Addresses https://github.com/solarwinds/apm-python/issues/538
Updates APM Python custom propagator to handle `baggage` and `tracestate` if injected by some upstream OTel instrumentors as dict instead of str:
* [opentelemetry-instrumentation-boto3sqs](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/d5dce5de996efcf2c2f85eed787c13f831095377/instrumentation/opentelemetry-instrumentation-boto3sqs/src/opentelemetry/instrumentation/boto3sqs/__init__.py#L77-L89)
* [opentelemetry-instrumentation-botocore](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/d5dce5de996efcf2c2f85eed787c13f831095377/instrumentation/opentelemetry-instrumentation-botocore/src/opentelemetry/instrumentation/botocore/extensions/_messaging.py#L26-L31)
APM-sanitized, non-empty baggage is …

NH-103629 Propagator custom `inject` checks for when baggage, tracestate set as dict

---

solarwinds_apm/configurator.py
tests/unit/test_configurator/conftest.py
tests/unit/test_configurator/test_configurator_configure_otel.py
tests/unit/test_configurator/test_configurator_logs_exporter.py

Replaces https://github.com/solarwinds/apm-python/pull/519
Adjusts APM Python's internal usage of upstream `OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED` and vendor-specific `SW_APM_EXPORT_LOGS_ENABLED`. The change is that logging provider and exporters are now _always_ set up when Agent Enabled.
The code is also cleaned up, but this is all the same:
1. `OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED` continues to have no default value (None) in APM Python.
2. `SW_APM_EXPORT_LOGS_ENABLED` continues to be False by default; it's an opt-in for users.
3. The OTEL config, only if set to True/False, continues to takes precedence over the SW_APM config.
4. The final config is still the condition for setting up the SDK log handler.
5. `OTEL_LOGS_EXPORTER` is still otlp http by default
6. …

NH-105440 Adjust APM Python OTLP logger component init

---

solarwinds_apm/apm_config.py
solarwinds_apm/configurator.py
solarwinds_apm/distro.py
tests/unit/test_apm_config/test_apm_config.py
tests/unit/test_apm_config/test_apm_config_calculate_metrics_enabled.py
tests/unit/test_configurator/test_configurator_metrics_exporter.py
tests/unit/test_distro.py

Replaces https://github.com/solarwinds/apm-python/pull/508
Breaking changes:
1. APM Python will now always generate and export SWO/vendor OTLP metrics by default (previously an opt-in), like other APM libraries.
2. Behaviour of `SW_APM_EXPORT_METRICS_ENABLED` is changed. It is now a config to opt out of non-SWO metrics, e.g. from Otel Python instrumentors.
I will put in a documentation update PR separately.

NH-105445 Breaking: update OTLP metrics export defaults and configs

---

.github/dependabot.yml

Outside the lambda test dir: simplifies dependabot deps checks so that there is one group, `otel-dependencies`, that will result in one PR -- instead of 3 for 3 `otel-*` groups!
Inside lambda test dir: also reduces to one PR, instead of 2

NH-105553 Simplify dependabot dep checks

---

solarwinds_apm/trace/serviceentry_processor.py
tests/unit/test_processors/test_serviceentry_processor.py

We don't need to resolve `http.route` when used as default txn name because of how it's [defined in the semconv](https://opentelemetry.io/docs/specs/semconv/attributes-registry/http/#http-route).

NH-72398 Nit: Don't need to resolve `http.route` as txn name

---

solarwinds_apm/sampler.py

Fixes small bug in the init of pure Python Oboe request counters for sampler-triggered OTLP metrics. Changes to use current global MeterProvider instead of passing a new one, so all metrics export via one reader etc.

NH-104796 Fix init of pure Python Oboe counters

---

solarwinds_apm/configurator.py
solarwinds_apm/trace/__init__.py
solarwinds_apm/trace/response_time_processor.py
tests/unit/test_configurator/conftest.py
tests/unit/test_configurator/test_configurator_configure_otel.py
tests/unit/test_configurator/test_configurator_span_processors.py
tests/unit/test_processors/test_otlp_metrics_processor.py

Renames APM Python `SolarWindsOTLPMetricsSpanProcessor` to simpler `ResponseTimeProcessor`. It's not so all-encompassing now that we've created the Pure Python sampler, and it's only responsible for recording `response_time` metrics.

NH-104796 Rename as ResponseTimeProcessor

---

solarwinds_apm/configurator.py
solarwinds_apm/sampler.py
tests/unit/test_configurator/conftest.py
tests/unit/test_configurator/test_configurator_configure_otel.py
tests/unit/test_configurator/test_configurator_sampler.py

A bit of cleanup along the way. Removes unused `oboe_api` from configurator, sampler init. Pure Python sampler in any mode does not need it.

NH-104999 Remove unused `oboe_api` from configurator, sampler init

---

solarwinds_apm/distro.py
tests/unit/test_distro.py

APM Python sets [OTLP exporter compression](https://github.com/open-telemetry/opentelemetry-python/blob/3644a1e17915aa7e8820dbacc1402338f9bfbb1b/opentelemetry-sdk/src/opentelemetry/sdk/environment_variables/__init__.py#L315-L330) to `"gzip"` by default. User can still configure compression to `"deflate"` if they wish.

NH-106956 OTLP exporter compression gzip by default

---

solarwinds_apm/configurator.py
tests/unit/test_configurator/test_configurator_metrics_exporter.py

All meters initialized under APM Python will use Delta as preferred default for aggregation temporality, not just histograms.

NH-106957 All meters under APM Python use Delta as preferred default

---

solarwinds_apm/apm_config.py
solarwinds_apm/configurator.py
tests/unit/test_apm_config/test_apm_config.py
tests/unit/test_configurator/test_configurator_init_reporter.py

Removes these user configuration keys as discussed on [other PR comment](https://github.com/solarwinds/apm-python/pull/552#discussion_r2014707559). They are no longer used to init Reporter and aren't needed by HttpSampler/JsonSampler either:
1. `ec2_metadata_timeout`
2. `proxy` (upstream exporters respect `grpc_proxy` and `HTTPS_PROXY`)
3. `reporter`

NH-104999 Remove unused configuration keys

---

solarwinds_apm/apm_config.py
tests/unit/test_apm_config/test_apm_config.py
tests/unit/test_apm_config/test_apm_config_agent_enabled.py
tests/unit/test_configurator/test_configurator_propagators.py

Removes the `OTEL_TRACES_EXPORTER` validity check that was part of calculating `agent_enabled`. Now that we let upstream handle configuration support (see https://github.com/solarwinds/apm-python/pull/578), APM side shouldn't duplicate or do something similar anymore.

NH-101363 Remove OTEL_TRACES_EXPORTER check when calculating agent_enabled

---

solarwinds_apm/api/__init__.py

Add back integer_response arg for compatibility.
https://swicloud.atlassian.net/browse/NH-107698

NH-107698 Python: Add back solarwinds_ready integer_response arg as no-op

---

solarwinds_apm/apm_config.py
tests/unit/test_apm_config/test_apm_config.py

- Fixed unset SW_APM_COLLECTOR yield to a `None` value from `apm_config['collector']` issue
- Added unit test case
https://swicloud.atlassian.net/browse/NH-107706

NH-107706 Python: Pure Python default collector

---

lambda/requirements-nodeps.txt
lambda/requirements.txt

Removes two grpcio-using dependencies from Lambda builds that both error with `ImportError: cannot import name ‘cygrpc' from 'grpc._cython' (/opt/python/grpc/_cython/__init__.py)`:
1. `opentelemetry-exporter-otlp-proto-grpc`, because grpc export also not supported by upstream's layer
2. `opentelemetry-instrumentation-grpc`, because its instrumentors fail (stacktrace in CloudWatch, though doesn't stop successful export of other instrumentors' telemetry)

NH-107791 Remove grpcio-using dependencies from Lambda

---

.github/workflows/build_publish_image_autoinstrumentation_beta.yaml
image/Dockerfile
image/Dockerfile-beta
image/requirements-nodeps-beta.txt

(1)
For NH-107711: changes autoinstrumentation image publish to only pre-install with Python 3.9. This will support Python 3.8-3.12 because no need to pre-install and copy multiple `.so` for now-removed dependencies.
(2)
For NH-107442: adds a second workflow, “Publish Beta APM Python Auto-Instrumentation“. Example run: https://github.com/solarwinds/apm-python/actions/runs/14524617943. Using [testrelease 4.0.0.5](https://test.pypi.org/project/solarwinds-apm/4.0.0.5/), this workflow was used to publish image with tag 4.0.0.5-beta (NOT latest) on [Docker Hub](https://hub.docker.com/r/solarwinds/autoinstrumentation-python/tags) and [ghcr.io](https://github.com/solarwinds/apm-python/pkgs/container/autoinstrumentation-python). See ticket comment for more testing. A little duplicative right now …

NH-107711 NH-107442 Update autoinstrumentation-image builds

---

solarwinds_apm/distro.py
tests/unit/test_distro.py

APM Python custom distro now only does `setdefault` for `OTEL_EXPORTER_OTLP_HEADERS` if the export endpoint is a SWO export endpoint. The endpoint is one of:
1. default
2. configured by user via `OTEL_EXPORTER_OTLP_ENDPOINT`
3. resolved from APM collector that was configured by user (`SW_APM_COLLECTOR`)

NH-107555 Set default headers if export endpoint is swo

---

solarwinds_apm/apm_config.py
solarwinds_apm/distro.py
tests/unit/test_apm_config/test_apm_config_calculate_collector.py
tests/unit/test_distro.py

Adds new ApmConfig class function to calculate `collector` as `environment Variable > config file > default`. Distro now uses this for `collector` resolution of export endpoint. This is needed because Configurator (and ApmConfig) init happen after Distro lifecycle has ended; Distro and Configurator can't share one ApmConfig due to lifecycles when [sitecustomize](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/748c92592d2f476199667629defce4a3bca9ecc9/opentelemetry-instrumentation/src/opentelemetry/instrumentation/auto_instrumentation/sitecustomize.py#L37-L39) is used.

NH-108028 Support config file collector endpoint resolution

---

solarwinds_apm/oboe/http_sampler.py

Reset last warning message if http_sampler recovered itself.
Found this issue during porting code from python to PHP
https://swicloud.atlassian.net/browse/NH-104807

NH-104807 - Python Reset warning message of http sampler

---

solarwinds_apm/oboe/oboe_sampler.py
tests/unit/test_oboe/test_oboe_sampler.py

sw.w3c.tracestate is not found in the span attributes.
It is because a wrong trace_state was used to check for the inbound trace_state. As a result, the wrong trace state yield a None and skip the attributes setup
Fixed by checking the trace_state from parent_span_context
https://swicloud.atlassian.net/browse/NH-108175

NH-108175 Python: Fix sw.w3c.tracestate attribute

---

solarwinds_apm/oboe/metrics.py

Adds units and descriptions to OTel counters for our metrics.
Already being added for the histogram: https://github.com/solarwinds/apm-python/blob/db06001fb4ea3570b0bfc9409d08d431fa3742dc/solarwinds_apm/trace/response_time_processor.py#L49-L53

NH-107450 Add units, description to OTel counters for metrics

---

solarwinds_apm/configurator.py
solarwinds_apm/sampler.py
tests/unit/test_api.py
tests/unit/test_sampler/test_sampler.py

Removes now-unnecessary param, `reporter`, at Pure Python sampler init. Re-adds a unit test.

NH-104999 Remove unnecessary param at Pure Python sampler init

---

tests/unit/test_apm_config/test_apm_config.py
tests/unit/test_apm_config/test_apm_config_agent_enabled.py
tests/unit/test_apm_config/test_apm_config_cnf_file.py

Cleans up ApmConfig unit tests because these don't exist anymore internally for ApmConfig:
1. liboboe log_filepath
2. liboboe log_type
3. liboboe log_settings
4. OboeAPI

NH-104999 Clean up ApmConfig unit tests

---

solarwinds_apm/apm_constants.py

Don't load LambdaDetector when outside lambda, otherwise upstream gives us a warning: `AwsLambdaResourceDetector failed: 'AWS_REGION'`.

NH-103814 Don't load LambdaDetector when outside lambda

---

tests/integration/test_base_sw_headers_attrs.py

Potential fix for [https://github.com/solarwinds/apm-python/security/code-scanning/446](https://github.com/solarwinds/apm-python/security/code-scanning/446)
The best way to fix this issue is to remove the unused import statement for `ParentBasedSwSampler`. This will clean up the code and eliminate the unnecessary dependency. The change should be made directly in the file `tests/integration/test_base_sw_headers_attrs.py` by deleting the specific import statement on line 37.

Potential fix for code scanning alert no. 446: Unused import

---

tests/unit/test_configurator/test_configurator_propagators.py

Potential fix for [https://github.com/solarwinds/apm-python/security/code-scanning/432](https://github.com/solarwinds/apm-python/security/code-scanning/432)
To fix the issue, we will remove the unused variable `test_configurator` and its assignment on line 93. Since the variable is not used and the assignment does not appear to have side effects, this change will not affect the functionality of the code. The rest of the method will remain unchanged.
---

Potential fix for code scanning alert no. 432: Unused local variable

---

tests/unit/test_oboe/test_sampler.py

Potential fix for [https://github.com/solarwinds/apm-python/security/code-scanning/357](https://github.com/solarwinds/apm-python/security/code-scanning/357)
To fix the issue, we will remove the unused `logging` import from line 8. This will eliminate the unnecessary dependency and improve code clarity. No other changes are required since the `logging` module is not used in the provided code.
---

Potential fix for code scanning alert no. 357: Unused import

---

tests/unit/test_oboe/test_oboe_sampler.py

Potential fix for [https://github.com/solarwinds/apm-python/security/code-scanning/356](https://github.com/solarwinds/apm-python/security/code-scanning/356)
To fix the issue, the unused `logging` import should be removed from the file. This will eliminate the unnecessary dependency and improve code readability. The change should be made on line 10 of the file `tests/unit/test_oboe/test_oboe_sampler.py`.
---

Potential fix for code scanning alert no. 356: Unused import

---

tests/unit/test_oboe/test_json_sampler.py

Potential fix for [https://github.com/solarwinds/apm-python/security/code-scanning/355](https://github.com/solarwinds/apm-python/security/code-scanning/355)
To fix the issue, we will remove the unused `logging` import from line 8. This will eliminate the unnecessary dependency and improve code readability. No other changes are required since the `logging` module is not used in the provided code.

Potential fix for code scanning alert no. 355: Unused import

---

tests/unit/test_oboe/test_http_sampler.py

Potential fix for [https://github.com/solarwinds/apm-python/security/code-scanning/354](https://github.com/solarwinds/apm-python/security/code-scanning/354)
To fix the issue, we will remove the unused `logging` import from line 6. This will clean up the code and eliminate the unnecessary dependency. No other changes are required since the `logging` module is not used in the provided code snippet.
---

Potential fix for code scanning alert no. 354: Unused import

---

tests/docker/install/_helper_run_install_tests.sh

Adjusts "Verify Installation" test dependencies following Pure Python. Generally the deps of each Linux distro can be reduced to "regular" Python and utils to curl/find/grep etc, without needing "dev" Python and g++.
We do add an Alpine dependency, `linux-headers`, needed since adding psutils dep in https://github.com/solarwinds/apm-python/pull/629. This will be needed after next release of APM Python.
Test run using this branch and APM Python 4.0.0: https://github.com/solarwinds/apm-python/actions/runs/14940259260

NH-108983 Adjust "Verify Installation" test dependencies following Pure Python

---

.github/workflows/verify_install.yaml
tests/docker/install/README.md
tests/docker/install/_helper_run_install_tests.sh
tests/docker/install/install_tests.sh

Updates "Verify Installation" CI/CD to be more automated. A `"local"` registry/source is now supported and is the default, which uses contents of the current branch to build sdist and wheel to do the test (not just PyPI/TestPyPI anymore). This allows us to automatically run "Verify Installation" with the other tox tests now on every PR and merge to `main` branch.
This branch was used to successfully run install tests from "local" (branch contents) by manual dispatch: https://github.com/solarwinds/apm-python/actions/runs/14985714435
And they also ran on this PR 😺

NH-108983 Update "Verify Installation" CI/CD for more automation

---

.github/workflows/verify_install.yaml
.github/workflows/verify_install_windows.yaml
tests/docker/install/windows/_helper_check_sdist.ps1
tests/docker/install/windows/_helper_check_wheel.ps1
tests/docker/install/windows/_helper_run_install_tests.ps1
tests/docker/install/windows/install_tests.ps1

Adds `verify_installation_windows` CI/CD to smoke test the installation of APM Python on `windows-latest` for the 5 supported Python versions. This will be run on every PR and push to main with current branch contents, and can be manually triggered to install from local (branch contents), TestPyPI, or PyPI -- like the update in https://github.com/solarwinds/apm-python/pull/635. This re-writes the existing `.sh` test scripts as `.ps1` for Windows compatibility.
Completed test runs:
* "local" (with correct job names!): https://github.com/solarwinds/apm-python/actions/runs/15008808953
* "testpypi": https://github.com/solarwinds/apm-python/actions/runs/15008683418/job/42173195998
* "pypi": https://github.com/solarwinds/apm-python/actions/runs/15008722309

NH-108983 Add verify_installation_windows CI/CD

---

.github/workflows/verify_install_macos.yaml
tests/docker/install/_helper_check_wheel.sh
tests/docker/install/_helper_run_install_tests.sh
tests/docker/install/install_tests.sh

Adds `verify_installation_macos` CI/CD to smoke test the installation of APM Python on `macos-latest` for the 5 supported Python versions. This will be run on every PR and push to main with current branch contents, and can be manually triggered to install from local (branch contents), TestPyPI, or PyPI -- like the updates in https://github.com/solarwinds/apm-python/pull/635 and https://github.com/solarwinds/apm-python/pull/636. MacOS is Unix-based so we use the existing Linux test scripts with minor adjustments.
Completed test run: https://github.com/solarwinds/apm-python/actions/runs/15009592518

NH-108983 Add verify_installation_macos CI/CD

---

README.md
pyproject.toml
tests/docker/install/README.md
tests/docker/install/_helper_check_sdist.sh
tests/docker/install/_helper_check_wheel.sh
tests/docker/install/windows/_helper_check_sdist.ps1
tests/docker/install/windows/_helper_check_wheel.ps1

`psutil` is now an optional dependency of APM Python. This isn't breaking because the initial addition of `psutil` has not yet been released.
From user point of view, system metrics generation is now an opt-in at time of installation:
* "Regular" install: `pip install solarwinds-apm`
* Opt into metrics generation: `pip install solarwinds-apm[system-metrics]`
I've updated the install tests to always opt in. Successful test runs:
- Linux https://github.com/solarwinds/apm-python/actions/runs/15055786278
- Mac https://github.com/solarwinds/apm-python/actions/runs/15055789490
- Windows https://github.com/solarwinds/apm-python/actions/runs/15055791947
I'm working on a separate PR for documentation update.

NH-110883 psutil becomes optional dep for APM Python

---

README.md
pyproject.toml
tests/docker/install/README.md
tests/docker/install/_helper_check_sdist.sh
tests/docker/install/_helper_check_wheel.sh
tests/docker/install/_helper_run_install_tests.sh
tests/docker/install/install_tests.sh
tests/docker/install/windows/_helper_check_sdist.ps1
tests/docker/install/windows/_helper_check_wheel.ps1
tests/docker/install/windows/install_tests.ps1

Remove `psutil` dependency -- not breaking because APM Python has not been released with the psutil dep.
Instead, we instruct users to install psutil separately to opt into system metrics export.

NH-110883 Remove psutil dependency

---

image/requirements.txt

Remove the system-metrics instrumentor pre-installation from k8s image publishes. This is a precaution against some performance and money penalties.

NH-111009 Remove system-metrics instrumentor pre-installation from k8s

---

solarwinds_apm/distro.py
tests/unit/test_distro.py

APM Python sets `"base2_exponential_bucket_histogram"` histogram aggregation by default. Currently this value is [hard-coded ](https://github.com/open-telemetry/opentelemetry-python/blob/12bcd4508e4aca43667450db090a50b9efab9963/exporter/opentelemetry-exporter-otlp-proto-common/src/opentelemetry/exporter/otlp/proto/common/_internal/metrics_encoder/__init__.py#L146-L148)in the upstream metrics exporter common.

NH-109170 Exponential histogram aggregation by default

---

.github/workflows/build_publish_lambda_layer.yaml
.github/workflows/run_tox_lint_format.yaml
.github/workflows/run_tox_tests.yaml
.github/workflows/verify_install.yaml
.github/workflows/verify_install_macos.yaml
.github/workflows/verify_install_windows.yaml
pyproject.toml
tests/docker/install/README.md
tests/docker/install/_helper_run_install_tests.sh
tests/docker/install/docker-compose.yml
tox.ini

Updates APM Python unit tests and installation/smoke tests to include Python 3.13 -- required some helper shell script changes. All pass on this PR's ci/cd.
Removes explicit Python version `Classifiers` from pyproject.toml to match upstream. We still have [requires-python](https://github.com/solarwinds/apm-python/pull/667/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L41) defined. Updates the tags for Lambda layer build too.

NH-115253 Add more Python 3.13 testing, update Lambda tags

---

scripts/lint_and_format.py

Potential fix for [https://github.com/solarwinds/apm-python/security/code-scanning/450](https://github.com/solarwinds/apm-python/security/code-scanning/450)
To fix the problem, simply remove the unused import statement `import os` from line 10 of `scripts/lint_and_format.py`. This change should be made only to the import statement itself, leaving all other code unchanged. No additional methods, imports, or definitions are required, as the rest of the code does not depend on the `os` module.

Potential fix for code scanning alert no. 450: Unused import

---

.github/workflows/build_publish_image_autoinstrumentation.yaml
.github/workflows/build_publish_image_autoinstrumentation_beta.yaml
.github/workflows/build_publish_lambda_layer.yaml
.github/workflows/build_publish_pypi_and_draft_release.yaml
.github/workflows/build_sdist_and_wheel.yaml
.github/workflows/codeql_analysis.yml
.github/workflows/create_release_pr.yaml
.github/workflows/create_testrelease_pr.yaml
.github/workflows/get_apm_python_version.yaml
.github/workflows/run_tox_lint_format.yaml
.github/workflows/run_tox_tests.yaml
.github/workflows/verify_install.yaml
.github/workflows/verify_install_macos.yaml
.github/workflows/verify_install_windows.yaml
tests/docker/install/docker-compose.yml

Updates CI/CD workflows with:
1. Upgrade to latest `checkout@v5` wherever possible
2. Still use `checkout@v4` for those containers/OS that don't use Node 24, which is Alpine < 3.17
3. Remove Alpine 3.12 testing since we [dropped support](https://documentation.solarwinds.com/en/success_center/observability/content/system_requirements/apm_requirements.htm#linux) a while ago.

NH-117515 Update workflow

---

tests/unit/test_configurator/conftest.py

Potential fix for [https://github.com/solarwinds/apm-python/security/code-scanning/451](https://github.com/solarwinds/apm-python/security/code-scanning/451)
To fix the problem, we must ensure that only valid keyword arguments are passed when calling `get_apmconfig_mocks`. Since `md_is_valid` is not a parameter of `get_apmconfig_mocks`, we should replace the unsupported `md_is_valid=False` argument with an appropriate supported argument. The function parameters are: `mocker, enabled=True, is_lambda=False, export_metrics_enabled=True`. If the intention was to mock an invalid metric export configuration, then we should pass `export_metrics_enabled=False` instead. Only line 183 (and its surrounding context) within the fixture `mock_apmconfig_enabled_md_invalid` (lines 177-186) needs changing. …

NH-119695 Potential fix for code scanning alert no. 451: Wrong name for an argument in a call
