CHANGELOG.md

Dedicated PR to update changelog with all changes since 0.9.0 so far.

NH-34752 Update changelog

---

CHANGELOG.md
solarwinds_apm/version.py

Testrelease 0.10.0.0, published to TestPyPI: https://test.pypi.org/project/solarwinds-apm/0.10.0.0/#files
Install tests from TestPyPI pass: https://github.com/solarwindscloud/solarwinds-apm-python/actions/runs/4854266187
tox tests on this branch pass.
Test traces:
* [SWO Django](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/DECE38E72D988ED9182BDB3A101150FF/627E5504BA769355/details/breakdown?perspective=requests&serviceId=e-1540126275982954496)
* [SWO FastAPI](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/DCF4C70808049138C377760AD1A1DAFF/0A7924EBA34BC05F/details/breakdown?perspective=requests&serviceId=e-1563388155741380608)
* [AO Django](https://my.appoptics.com/apm/123092/services/django-app-a-ot/traces/7192621CB5261351624F9574C5B1741400000000?duration= …

Testrelease 0.10.0.0

---

CHANGELOG.md
solarwinds_apm/version.py

Testrelease 0.12.1.0 for APM Python library.
e2e test traces:
* [SWO Django](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/D914E6D9BF76CF06BB35254F60ADDC65/DD58522D36F2D155/details/breakdown?perspective=requests&serviceId=e-1540126275982954496&sort_by_breakdown=SpanLayer&sort_order_breakdown=ascending)
* [SWO FastAPI](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/3437730753442A918EBF3E3A521DD7BC/6BD8724022989F62/details/breakdown?perspective=requests&serviceId=e-1563388155741380608)
* [AO Django](https://my.appoptics.com/apm/123092/services/django-app-a-ot/traces/8139E832B4C1C86C90CD5472C796EF3500000000?duration=3600)
* [AO FastAPI](https://my.appoptics.com/apm/123092/services/asgi_app_ot/traces/CCA444B7003F79394B8BA2AB8ED919DC …

Testrelease 0.12.1.0

---

CHANGELOG.md
solarwinds_apm/version.py

Testrelease 0.13.0.0 for APM Python.
tox unit tests pass on this PR.
Test traces:
* [SWO Django](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/C051FC7C274BF7E7807DF228C6DAC49D/FEE3742118460B9C/details/breakdown?perspective=requests&serviceId=e-1540126275982954496&sort_by_breakdown=spanLayer&sort_order_breakdown=ascending)
* [SWO FastAPI](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/0AADC8E98FDC4CAF7DEF0F3C08C6CDD2/F3BE0D73F3B837E1/details/breakdown?perspective=requests&serviceId=e-1563388155741380608)
* [AO Django](https://my.appoptics.com/apm/123092/services/django-app-a-ot/traces/421F21CB16010B13639DA8D7987BCED400000000?duration=3600)
* [AO FastAPI](https://my.appoptics.com/apm/123092/services/asgi_app_ot/traces/0A34DFF8819960E742E90A31526702180000000 …

NH-45494 Testrelease 0.13.0.0

---

CHANGELOG.md
solarwinds_apm/version.py

APM Python library testrelease 0.14.0.0.
Test traces from local install:
* [SWO Django](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/646D40220C53017B4FD546980D1FD86B/77BB572D5B5B83C9/details/breakdown?perspective=requests&serviceId=e-1540126275982954496&sort_by_breakdown=spanLayer&sort_order_breakdown=ascending)
* [SWO FastAPI](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/ED1613AB485755397A49AE3943367A80/56540D50CECAB67D/details/breakdown?perspective=requests&serviceId=e-1563388155741380608&sort_by_breakdown=spanLayer&sort_order_breakdown=ascending)
* [AO Django](https://my.appoptics.com/apm/123092/services/django-app-a-ot/traces/77FE22144784C4195C06FE949185302F00000000?duration=3600)
* [AO …

NH-49969 Testrelease 0.14.0.0

---

CODEOWNERS

NH-55271 Add CODEOWNERS

---

CHANGELOG.md
solarwinds_apm/version.py

Testrelease APM Python library 0.16.0.0
Test traces:
* [SWO Django](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/0D5C6E2BB79681DC895223A4A16736A2/4C71F8952AB0287E/details/breakdown?perspective=requests&serviceId=e-1540126275982954496&sort_by_breakdown=spanLayer&sort_order_breakdown=ascending)
* [SWO FastAPI](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/ED23FBCE98D4410588A086DE3D3DB3F0/E03BA554F9101F12/details/breakdown?perspective=requests&serviceId=e-1563388155741380608&sort_by_breakdown=spanLayer&sort_order_breakdown=ascending)
* [AO Django](https://my.appoptics.com/apm/123092/services/django-app-a-ot/traces/6072BE56E7F632F324A77375E7DBA92C00000000?duration=3600)
* [AO …

NH-55293 Testrelease 0.16.0.0

---

.github/workflows/verify_install.yaml
tests/docker/install/docker-compose.yml

Add Debian 11 install tests for on local and in GH workflow.
GH test run here: https://github.com/solarwindscloud/solarwinds-apm-python/actions/runs/6474729597/job/17580341321

NH-63906 Add Debian 11 install tests

---

.github/workflows/build_publish_pypi_and_draft_release.yaml
.github/workflows/create_release_pr.yaml

Fix workflow yaml syntax so I can publish, oops.

NH-65933 Fix workflow yaml syntax

---

CHANGELOG.md
solarwinds_apm/version.py

See CHANGELOG for updates since 0.17.0.
Test traces:
- [SWO Django](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/282E6A921A38B0792BC55D28990514C7/F8F5CC5153A62C5F/details/breakdown?perspective=requests&serviceId=e-1655756171056209920&sort_by_breakdown=spanLayer&sort_order_breakdown=ascending)
- [SWO FastAPI](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/CADC48DA1D144830EFF7D7DE76C05E97/B6EEA8A984AEBE22/details/breakdown?perspective=requests&serviceId=e-1655757500269252608&sort_by_breakdown=spanLayer&sort_order_breakdown=ascending)
- [AO Django](https://my.appoptics.com/apm/123092/services/django-app-a-ot/traces/7CF445562EB5A2B283CE2244C127AC9800000000?duration=3600&search=django)
- [AO …

Publish APM Python 0.18.0

---

CHANGELOG.md
solarwinds_apm/version.py

Contents of Testrelease 1.0.0.0 publish and release.
Test traces:
* [SWO Django](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/FA8B6D26779EC23BA4882ACB8BC4CE04/529FD036B111309A/details/breakdown?perspective=requests&serviceId=e-1655756171056209920&sort_by_breakdown=spanLayer&sort_order_breakdown=ascending)
* [SWO FastAPI](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/E74BFCDEA398164C73F40F03FCD5B3D8/683EC65EEBE2BAFE/details/breakdown?perspective=requests&serviceId=e-1655757500269252608&sort_by_breakdown=spanLayer&sort_order_breakdown=ascending)
* [AO Django](https://my.appoptics.com/apm/123092/services/django-app-a-ot/traces/84266DDCBFFAB6C401EEA0DB4222A64E00000000?duration=3600)
* [AO …

Testrelease 1.0.0.0

---

.github/workflows/build_publish_pypi_and_draft_release.yaml
.github/workflows/create_release_pr.yaml

Fixes Create Release PR action, example run: https://github.com/solarwinds/apm-python/actions/runs/6949351866/job/18907266403
Should also fix Draft Release action but I don't want to try that until next release.

NH-66239 Fix release actions

---

solarwinds_apm/configurator.py
solarwinds_apm/otlp_metrics_processor.py
solarwinds_apm/trace/__init__.py
solarwinds_apm/trace/forceflush_processor.py
tests/unit/test_configurator/conftest.py
tests/unit/test_configurator/test_configurator_span_processors.py

Factor out a new force_flush span processor separate from OTLPMetricsSpanProcessor. First step towards refactoring the APM Python span processors.

NH-65061 Add separate force_flush span processor

---

.github/dependabot.yml

Adds dependabot config for APM Python to do dependency updates. See also comment: https://swicloud.atlassian.net/browse/NH-66478?focusedCommentId=2584965

NH-66478 Add dependabot config

---

CHANGELOG.md
solarwinds_apm/version.py

Contents for release of APM Python version 1.1.0
Test traces from regular instrumentation:
- [SWO Django](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/75D9E99A21704774C00A67F2B3A97569/1E807A0A2A9AED44/details)
- [SWO FastAPI](https://my.na-01.cloud.solarwinds.com/140638900734749696/traces/6F76D9768008F587927CEDB9DC3D4521/CFE5541E174114D8/details/breakdown)
- [AO Django](https://my.appoptics.com/apm/123092/services/django-app-a-ot/traces/CD6607FBECB1A4511043BD65042AF2E600000000?duration=3600)
- [AO FastAPI](https://my.appoptics.com/apm/123092/services/asgi_app_ot/traces/03EAE4B147EEF4E1C260E326961A278300000000?duration=3600)
Smoke tests will be performed immediately after PyPI publish.

NH-70036 APM Python version 1.1.0

---

CHANGELOG.md
solarwinds_apm/apm_meter_manager.py
solarwinds_apm/trace/otlp_metrics_processor.py

These are no longer needed; see ticket description.
Also updates changelog for another PR I forgot to do

NH-67392 Remove unneeded todos

---

solarwinds_apm/trace/inbound_metrics_processor.py

Remove some todos because these already no longer log after a [previous PR](https://github.com/solarwinds/apm-python/pull/254).

NH-69129 Remove todos

---

solarwinds_apm/apm_noop.py
solarwinds_apm/semconv/trace/__init__.py

Fixes some new lint complaints in old code.

NH-100773 Appease lint

---

image/requirements-nodeps.txt

Bump auto-instrumentation image APM Python dependency for next publish.

NH-102110 Update auto-instrumentation image APM dep

---

.github/workflows/build_publish_image_autoinstrumentation.yaml

Update APM Python autoinstrumentation image builds to use OAT, and scans to use different PAT.

NH-100901 Update autoinstrumentation-python image builds

---

solarwinds_apm/oboe/http_sampler.py

Suppress tracing when HTTP getSettings, else too many unnecessary traces.

NH-106059 Suppress tracing when HTTP getsettings

---

solarwinds_apm/oboe/oboe_sampler.py
tests/unit/test_oboe/test_oboe_sampler.py

Housekept spantype logic in oboe_sampler.py
https://swicloud.atlassian.net/browse/NH-104999

NH-104999 - Housekept spantype logic

---

solarwinds_apm/configurator.py

Init and register upstream NoOpMeterProvider, NoOpLoggerProvider if not doing exporters. (It's already being done for TracerProvider).

NH-105013 Use more upstream NoOpXProvider 

---

solarwinds_apm/api/__init__.py
solarwinds_apm/apm_ready.py
solarwinds_apm/tracer_provider.py
tests/unit/test_api.py

- Implemented solarwinds_ready api function
- Added tests
https://swicloud.atlassian.net/browse/NH-104961

NH-104961 - Python: Pure Python WaitUntilReady SDK

---

lambda/requirements.txt
solarwinds_apm/apm_constants.py
solarwinds_apm/distro.py

Updates Lambda dependencies and specifies resource detectors for Lambda environment.
Expands on https://github.com/solarwinds/apm-python/pull/577. See ticket comment for some testing.

NH-107714 lambda resource detect

---

solarwinds_apm/distro.py
tests/unit/test_distro.py

Added deducing mode from SW_APM_COLLECTOR
https://swicloud.atlassian.net/browse/NH-102467

NH-102467 Python: Add deducing of export mode from SW_APM_COLLECTOR

---

solarwinds_apm/apm_config.py

Stop logging that Lambda mode experimental!

NH-107912 Stop logging that Lambda mode experimental

---

.flake8
.isort.cfg
MANIFEST.in
pyproject.toml
scripts/lint_and_format.py
setup.py
solarwinds_apm/api/__init__.py
tests/unit/test_apm_config/test_apm_config.py

Fully remove extension mentions from linting, builds.

NH-104999 Fully remove extension from linting, builds

---

tests/unit/test_configurator/conftest.py

Remove dead ApmConfig test fixtures that were used to mock extension.

NH-104999 Remove dead ApmConfig test fixtures

---

solarwinds_apm/trace/serviceentry_processor.py

Fixed function signature
https://swicloud.atlassian.net/browse/NH-110601

NH-110601 - Python: Fix function signature

---

solarwinds_apm/oboe/metrics.py

Nits
- Updated counter description as there are other factors to not sample the request ( e.g. the dice returned unsampled)

Updated description

---

solarwinds_apm/oboe/metrics.py
solarwinds_apm/trace/response_time_processor.py

Synced the exact wording in metrics description
https://swicloud.atlassian.net/browse/NH-107450

NH-107450 - Synced the metrics description wording

---

solarwinds_apm/configurator.py
tests/unit/test_configurator/test_configurator_configure_otel.py

Configurator sets Resource with `service.instance.id`.

NH-110318 Configurator sets Resource with service.instance.id

---

solarwinds_apm/oboe/http_sampler.py

Cleaned up unused constant in http_sampler.py

NH-116785 - Python: remove unused http_sampler constants

---

README.md

Fixes badges on Readme and their position with header.

NH-118446 Fix badges and position
